packages:
  - packages/platform/*
  - packages/standard/*
  - packages/third-party/*
  - packages/standard/*/generated/*
  - packages/third-party/*/generated/*

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@pulumi/command"
  - "@pulumi/kubernetes"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - classic-level
  - esbuild
  - less
  - nx
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - "@prisma/engines"

overrides:
  "@prisma/adapter-libsql": 7.4.1
  "@prisma/client": 7.4.1
  "@prisma/driver-adapter-utils": 7.4.1
  prisma: 7.4.1
