import type { Cli } from "clipanion"
import {
  ComponentGetCommand,
  ComponentListCommand,
  ComponentSchemaCommand,
  ContextAddCommand,
  ContextDeleteCommand,
  ContextListCommand,
  ContextShowCommand,
  ContextTestCommand,
  ContextUseCommand,
  EntityGetCommand,
  EntityListCommand,
  HubCreateCommand,
  HubDeleteCommand,
  HubGetCommand,
  HubListCommand,
  HubUpdateCommand,
  InstanceArgumentsGetCommand,
  InstanceArgumentsPatchCommand,
  InstanceCreateCommand,
  InstanceDeleteCommand,
  InstanceGetCommand,
  InstanceListCommand,
  InstanceRenameCommand,
  InstanceUpdateCommand,
  LibraryListCommand,
  ModelCreateCommand,
  ModelGetCommand,
  OperationCancelCommand,
  OperationCancelInstanceCommand,
  OperationGetCommand,
  OperationLaunchCommand,
  OperationListCommand,
  OperationLogsCommand,
  OperationPlanCommand,
  OperationRunCommand,
  OperationWaitCommand,
  ProjectGetCommand,
  ProjectListCommand,
  ProjectUnsetCommand,
  ProjectUseCommand,
  StateGetCommand,
  StateListCommand,
} from "./commands"

export default function registerRemoteCommands(cli: Cli): void {
  cli.register(ContextAddCommand)
  cli.register(ContextListCommand)
  cli.register(ContextShowCommand)
  cli.register(ContextUseCommand)
  cli.register(ContextDeleteCommand)
  cli.register(ContextTestCommand)
  cli.register(ProjectListCommand)
  cli.register(ProjectGetCommand)
  cli.register(ProjectUseCommand)
  cli.register(ProjectUnsetCommand)
  cli.register(LibraryListCommand)
  cli.register(ComponentListCommand)
  cli.register(ComponentGetCommand)
  cli.register(ComponentSchemaCommand)
  cli.register(EntityListCommand)
  cli.register(EntityGetCommand)
  cli.register(ModelGetCommand)
  cli.register(ModelCreateCommand)
  cli.register(InstanceListCommand)
  cli.register(InstanceGetCommand)
  cli.register(InstanceArgumentsGetCommand)
  cli.register(InstanceArgumentsPatchCommand)
  cli.register(InstanceCreateCommand)
  cli.register(InstanceUpdateCommand)
  cli.register(InstanceRenameCommand)
  cli.register(InstanceDeleteCommand)
  cli.register(HubListCommand)
  cli.register(HubGetCommand)
  cli.register(HubCreateCommand)
  cli.register(HubUpdateCommand)
  cli.register(HubDeleteCommand)
  cli.register(StateListCommand)
  cli.register(StateGetCommand)
  cli.register(OperationPlanCommand)
  cli.register(OperationLaunchCommand)
  cli.register(OperationRunCommand)
  cli.register(OperationListCommand)
  cli.register(OperationGetCommand)
  cli.register(OperationWaitCommand)
  cli.register(OperationLogsCommand)
  cli.register(OperationCancelCommand)
  cli.register(OperationCancelInstanceCommand)
}
