
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServiceAccountBackendRoleBinding` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg.ts';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ServiceAccountBackendRoleBinding
 * A backend role binding grants a backend role to a backend service account.
 */
export type ServiceAccountBackendRoleBindingModel = runtime.Types.Result.DefaultSelection<Prisma.$ServiceAccountBackendRoleBindingPayload>

export type AggregateServiceAccountBackendRoleBinding = {
  _count: ServiceAccountBackendRoleBindingCountAggregateOutputType | null
  _min: ServiceAccountBackendRoleBindingMinAggregateOutputType | null
  _max: ServiceAccountBackendRoleBindingMaxAggregateOutputType | null
}

export type ServiceAccountBackendRoleBindingMinAggregateOutputType = {
  roleId: string | null
  serviceAccountId: string | null
  createdAt: Date | null
}

export type ServiceAccountBackendRoleBindingMaxAggregateOutputType = {
  roleId: string | null
  serviceAccountId: string | null
  createdAt: Date | null
}

export type ServiceAccountBackendRoleBindingCountAggregateOutputType = {
  roleId: number
  serviceAccountId: number
  createdAt: number
  _all: number
}


export type ServiceAccountBackendRoleBindingMinAggregateInputType = {
  roleId?: true
  serviceAccountId?: true
  createdAt?: true
}

export type ServiceAccountBackendRoleBindingMaxAggregateInputType = {
  roleId?: true
  serviceAccountId?: true
  createdAt?: true
}

export type ServiceAccountBackendRoleBindingCountAggregateInputType = {
  roleId?: true
  serviceAccountId?: true
  createdAt?: true
  _all?: true
}

export type ServiceAccountBackendRoleBindingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceAccountBackendRoleBinding to aggregate.
   */
  where?: Prisma.ServiceAccountBackendRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceAccountBackendRoleBindings to fetch.
   */
  orderBy?: Prisma.ServiceAccountBackendRoleBindingOrderByWithRelationInput | Prisma.ServiceAccountBackendRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceAccountBackendRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceAccountBackendRoleBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServiceAccountBackendRoleBindings
  **/
  _count?: true | ServiceAccountBackendRoleBindingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceAccountBackendRoleBindingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceAccountBackendRoleBindingMaxAggregateInputType
}

export type GetServiceAccountBackendRoleBindingAggregateType<T extends ServiceAccountBackendRoleBindingAggregateArgs> = {
      [P in keyof T & keyof AggregateServiceAccountBackendRoleBinding]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServiceAccountBackendRoleBinding[P]>
    : Prisma.GetScalarType<T[P], AggregateServiceAccountBackendRoleBinding[P]>
}




export type ServiceAccountBackendRoleBindingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceAccountBackendRoleBindingWhereInput
  orderBy?: Prisma.ServiceAccountBackendRoleBindingOrderByWithAggregationInput | Prisma.ServiceAccountBackendRoleBindingOrderByWithAggregationInput[]
  by: Prisma.ServiceAccountBackendRoleBindingScalarFieldEnum[] | Prisma.ServiceAccountBackendRoleBindingScalarFieldEnum
  having?: Prisma.ServiceAccountBackendRoleBindingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceAccountBackendRoleBindingCountAggregateInputType | true
  _min?: ServiceAccountBackendRoleBindingMinAggregateInputType
  _max?: ServiceAccountBackendRoleBindingMaxAggregateInputType
}

export type ServiceAccountBackendRoleBindingGroupByOutputType = {
  roleId: string
  serviceAccountId: string
  createdAt: Date
  _count: ServiceAccountBackendRoleBindingCountAggregateOutputType | null
  _min: ServiceAccountBackendRoleBindingMinAggregateOutputType | null
  _max: ServiceAccountBackendRoleBindingMaxAggregateOutputType | null
}

type GetServiceAccountBackendRoleBindingGroupByPayload<T extends ServiceAccountBackendRoleBindingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceAccountBackendRoleBindingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceAccountBackendRoleBindingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceAccountBackendRoleBindingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceAccountBackendRoleBindingGroupByOutputType[P]>
      }
    >
  >



export type ServiceAccountBackendRoleBindingWhereInput = {
  AND?: Prisma.ServiceAccountBackendRoleBindingWhereInput | Prisma.ServiceAccountBackendRoleBindingWhereInput[]
  OR?: Prisma.ServiceAccountBackendRoleBindingWhereInput[]
  NOT?: Prisma.ServiceAccountBackendRoleBindingWhereInput | Prisma.ServiceAccountBackendRoleBindingWhereInput[]
  roleId?: Prisma.StringFilter<"ServiceAccountBackendRoleBinding"> | string
  serviceAccountId?: Prisma.StringFilter<"ServiceAccountBackendRoleBinding"> | string
  createdAt?: Prisma.DateTimeFilter<"ServiceAccountBackendRoleBinding"> | Date | string
  role?: Prisma.XOR<Prisma.BackendRoleScalarRelationFilter, Prisma.BackendRoleWhereInput>
  serviceAccount?: Prisma.XOR<Prisma.BackendServiceAccountScalarRelationFilter, Prisma.BackendServiceAccountWhereInput>
}

export type ServiceAccountBackendRoleBindingOrderByWithRelationInput = {
  roleId?: Prisma.SortOrder
  serviceAccountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  role?: Prisma.BackendRoleOrderByWithRelationInput
  serviceAccount?: Prisma.BackendServiceAccountOrderByWithRelationInput
}

export type ServiceAccountBackendRoleBindingWhereUniqueInput = Prisma.AtLeast<{
  roleId_serviceAccountId?: Prisma.ServiceAccountBackendRoleBindingRoleIdServiceAccountIdCompoundUniqueInput
  AND?: Prisma.ServiceAccountBackendRoleBindingWhereInput | Prisma.ServiceAccountBackendRoleBindingWhereInput[]
  OR?: Prisma.ServiceAccountBackendRoleBindingWhereInput[]
  NOT?: Prisma.ServiceAccountBackendRoleBindingWhereInput | Prisma.ServiceAccountBackendRoleBindingWhereInput[]
  roleId?: Prisma.StringFilter<"ServiceAccountBackendRoleBinding"> | string
  serviceAccountId?: Prisma.StringFilter<"ServiceAccountBackendRoleBinding"> | string
  createdAt?: Prisma.DateTimeFilter<"ServiceAccountBackendRoleBinding"> | Date | string
  role?: Prisma.XOR<Prisma.BackendRoleScalarRelationFilter, Prisma.BackendRoleWhereInput>
  serviceAccount?: Prisma.XOR<Prisma.BackendServiceAccountScalarRelationFilter, Prisma.BackendServiceAccountWhereInput>
}, "roleId_serviceAccountId">

export type ServiceAccountBackendRoleBindingOrderByWithAggregationInput = {
  roleId?: Prisma.SortOrder
  serviceAccountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ServiceAccountBackendRoleBindingCountOrderByAggregateInput
  _max?: Prisma.ServiceAccountBackendRoleBindingMaxOrderByAggregateInput
  _min?: Prisma.ServiceAccountBackendRoleBindingMinOrderByAggregateInput
}

export type ServiceAccountBackendRoleBindingScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServiceAccountBackendRoleBindingScalarWhereWithAggregatesInput | Prisma.ServiceAccountBackendRoleBindingScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServiceAccountBackendRoleBindingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServiceAccountBackendRoleBindingScalarWhereWithAggregatesInput | Prisma.ServiceAccountBackendRoleBindingScalarWhereWithAggregatesInput[]
  roleId?: Prisma.StringWithAggregatesFilter<"ServiceAccountBackendRoleBinding"> | string
  serviceAccountId?: Prisma.StringWithAggregatesFilter<"ServiceAccountBackendRoleBinding"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ServiceAccountBackendRoleBinding"> | Date | string
}

export type ServiceAccountBackendRoleBindingCreateInput = {
  createdAt?: Date | string
  role: Prisma.BackendRoleCreateNestedOneWithoutServiceAccountBindingsInput
  serviceAccount: Prisma.BackendServiceAccountCreateNestedOneWithoutRoleBindingsInput
}

export type ServiceAccountBackendRoleBindingUncheckedCreateInput = {
  roleId: string
  serviceAccountId: string
  createdAt?: Date | string
}

export type ServiceAccountBackendRoleBindingUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.BackendRoleUpdateOneRequiredWithoutServiceAccountBindingsNestedInput
  serviceAccount?: Prisma.BackendServiceAccountUpdateOneRequiredWithoutRoleBindingsNestedInput
}

export type ServiceAccountBackendRoleBindingUncheckedUpdateInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceAccountBackendRoleBindingCreateManyInput = {
  roleId: string
  serviceAccountId: string
  createdAt?: Date | string
}

export type ServiceAccountBackendRoleBindingUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceAccountBackendRoleBindingUncheckedUpdateManyInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceAccountBackendRoleBindingListRelationFilter = {
  every?: Prisma.ServiceAccountBackendRoleBindingWhereInput
  some?: Prisma.ServiceAccountBackendRoleBindingWhereInput
  none?: Prisma.ServiceAccountBackendRoleBindingWhereInput
}

export type ServiceAccountBackendRoleBindingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ServiceAccountBackendRoleBindingRoleIdServiceAccountIdCompoundUniqueInput = {
  roleId: string
  serviceAccountId: string
}

export type ServiceAccountBackendRoleBindingCountOrderByAggregateInput = {
  roleId?: Prisma.SortOrder
  serviceAccountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ServiceAccountBackendRoleBindingMaxOrderByAggregateInput = {
  roleId?: Prisma.SortOrder
  serviceAccountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ServiceAccountBackendRoleBindingMinOrderByAggregateInput = {
  roleId?: Prisma.SortOrder
  serviceAccountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ServiceAccountBackendRoleBindingCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutRoleInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.ServiceAccountBackendRoleBindingCreateWithoutRoleInput[] | Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutRoleInput | Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.ServiceAccountBackendRoleBindingCreateManyRoleInputEnvelope
  connect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
}

export type ServiceAccountBackendRoleBindingUncheckedCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutRoleInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.ServiceAccountBackendRoleBindingCreateWithoutRoleInput[] | Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutRoleInput | Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.ServiceAccountBackendRoleBindingCreateManyRoleInputEnvelope
  connect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
}

export type ServiceAccountBackendRoleBindingUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutRoleInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.ServiceAccountBackendRoleBindingCreateWithoutRoleInput[] | Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutRoleInput | Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.ServiceAccountBackendRoleBindingUpsertWithWhereUniqueWithoutRoleInput | Prisma.ServiceAccountBackendRoleBindingUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.ServiceAccountBackendRoleBindingCreateManyRoleInputEnvelope
  set?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  delete?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  connect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  update?: Prisma.ServiceAccountBackendRoleBindingUpdateWithWhereUniqueWithoutRoleInput | Prisma.ServiceAccountBackendRoleBindingUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.ServiceAccountBackendRoleBindingUpdateManyWithWhereWithoutRoleInput | Prisma.ServiceAccountBackendRoleBindingUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.ServiceAccountBackendRoleBindingScalarWhereInput | Prisma.ServiceAccountBackendRoleBindingScalarWhereInput[]
}

export type ServiceAccountBackendRoleBindingUncheckedUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutRoleInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.ServiceAccountBackendRoleBindingCreateWithoutRoleInput[] | Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutRoleInput | Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.ServiceAccountBackendRoleBindingUpsertWithWhereUniqueWithoutRoleInput | Prisma.ServiceAccountBackendRoleBindingUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.ServiceAccountBackendRoleBindingCreateManyRoleInputEnvelope
  set?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  delete?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  connect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  update?: Prisma.ServiceAccountBackendRoleBindingUpdateWithWhereUniqueWithoutRoleInput | Prisma.ServiceAccountBackendRoleBindingUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.ServiceAccountBackendRoleBindingUpdateManyWithWhereWithoutRoleInput | Prisma.ServiceAccountBackendRoleBindingUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.ServiceAccountBackendRoleBindingScalarWhereInput | Prisma.ServiceAccountBackendRoleBindingScalarWhereInput[]
}

export type ServiceAccountBackendRoleBindingCreateNestedManyWithoutServiceAccountInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutServiceAccountInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutServiceAccountInput> | Prisma.ServiceAccountBackendRoleBindingCreateWithoutServiceAccountInput[] | Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutServiceAccountInput[]
  connectOrCreate?: Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutServiceAccountInput | Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutServiceAccountInput[]
  createMany?: Prisma.ServiceAccountBackendRoleBindingCreateManyServiceAccountInputEnvelope
  connect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
}

export type ServiceAccountBackendRoleBindingUncheckedCreateNestedManyWithoutServiceAccountInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutServiceAccountInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutServiceAccountInput> | Prisma.ServiceAccountBackendRoleBindingCreateWithoutServiceAccountInput[] | Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutServiceAccountInput[]
  connectOrCreate?: Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutServiceAccountInput | Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutServiceAccountInput[]
  createMany?: Prisma.ServiceAccountBackendRoleBindingCreateManyServiceAccountInputEnvelope
  connect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
}

export type ServiceAccountBackendRoleBindingUpdateManyWithoutServiceAccountNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutServiceAccountInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutServiceAccountInput> | Prisma.ServiceAccountBackendRoleBindingCreateWithoutServiceAccountInput[] | Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutServiceAccountInput[]
  connectOrCreate?: Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutServiceAccountInput | Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutServiceAccountInput[]
  upsert?: Prisma.ServiceAccountBackendRoleBindingUpsertWithWhereUniqueWithoutServiceAccountInput | Prisma.ServiceAccountBackendRoleBindingUpsertWithWhereUniqueWithoutServiceAccountInput[]
  createMany?: Prisma.ServiceAccountBackendRoleBindingCreateManyServiceAccountInputEnvelope
  set?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  delete?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  connect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  update?: Prisma.ServiceAccountBackendRoleBindingUpdateWithWhereUniqueWithoutServiceAccountInput | Prisma.ServiceAccountBackendRoleBindingUpdateWithWhereUniqueWithoutServiceAccountInput[]
  updateMany?: Prisma.ServiceAccountBackendRoleBindingUpdateManyWithWhereWithoutServiceAccountInput | Prisma.ServiceAccountBackendRoleBindingUpdateManyWithWhereWithoutServiceAccountInput[]
  deleteMany?: Prisma.ServiceAccountBackendRoleBindingScalarWhereInput | Prisma.ServiceAccountBackendRoleBindingScalarWhereInput[]
}

export type ServiceAccountBackendRoleBindingUncheckedUpdateManyWithoutServiceAccountNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutServiceAccountInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutServiceAccountInput> | Prisma.ServiceAccountBackendRoleBindingCreateWithoutServiceAccountInput[] | Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutServiceAccountInput[]
  connectOrCreate?: Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutServiceAccountInput | Prisma.ServiceAccountBackendRoleBindingCreateOrConnectWithoutServiceAccountInput[]
  upsert?: Prisma.ServiceAccountBackendRoleBindingUpsertWithWhereUniqueWithoutServiceAccountInput | Prisma.ServiceAccountBackendRoleBindingUpsertWithWhereUniqueWithoutServiceAccountInput[]
  createMany?: Prisma.ServiceAccountBackendRoleBindingCreateManyServiceAccountInputEnvelope
  set?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  delete?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  connect?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput | Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput[]
  update?: Prisma.ServiceAccountBackendRoleBindingUpdateWithWhereUniqueWithoutServiceAccountInput | Prisma.ServiceAccountBackendRoleBindingUpdateWithWhereUniqueWithoutServiceAccountInput[]
  updateMany?: Prisma.ServiceAccountBackendRoleBindingUpdateManyWithWhereWithoutServiceAccountInput | Prisma.ServiceAccountBackendRoleBindingUpdateManyWithWhereWithoutServiceAccountInput[]
  deleteMany?: Prisma.ServiceAccountBackendRoleBindingScalarWhereInput | Prisma.ServiceAccountBackendRoleBindingScalarWhereInput[]
}

export type ServiceAccountBackendRoleBindingCreateWithoutRoleInput = {
  createdAt?: Date | string
  serviceAccount: Prisma.BackendServiceAccountCreateNestedOneWithoutRoleBindingsInput
}

export type ServiceAccountBackendRoleBindingUncheckedCreateWithoutRoleInput = {
  serviceAccountId: string
  createdAt?: Date | string
}

export type ServiceAccountBackendRoleBindingCreateOrConnectWithoutRoleInput = {
  where: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutRoleInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutRoleInput>
}

export type ServiceAccountBackendRoleBindingCreateManyRoleInputEnvelope = {
  data: Prisma.ServiceAccountBackendRoleBindingCreateManyRoleInput | Prisma.ServiceAccountBackendRoleBindingCreateManyRoleInput[]
  skipDuplicates?: boolean
}

export type ServiceAccountBackendRoleBindingUpsertWithWhereUniqueWithoutRoleInput = {
  where: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
  update: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingUpdateWithoutRoleInput, Prisma.ServiceAccountBackendRoleBindingUncheckedUpdateWithoutRoleInput>
  create: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutRoleInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutRoleInput>
}

export type ServiceAccountBackendRoleBindingUpdateWithWhereUniqueWithoutRoleInput = {
  where: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
  data: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingUpdateWithoutRoleInput, Prisma.ServiceAccountBackendRoleBindingUncheckedUpdateWithoutRoleInput>
}

export type ServiceAccountBackendRoleBindingUpdateManyWithWhereWithoutRoleInput = {
  where: Prisma.ServiceAccountBackendRoleBindingScalarWhereInput
  data: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingUpdateManyMutationInput, Prisma.ServiceAccountBackendRoleBindingUncheckedUpdateManyWithoutRoleInput>
}

export type ServiceAccountBackendRoleBindingScalarWhereInput = {
  AND?: Prisma.ServiceAccountBackendRoleBindingScalarWhereInput | Prisma.ServiceAccountBackendRoleBindingScalarWhereInput[]
  OR?: Prisma.ServiceAccountBackendRoleBindingScalarWhereInput[]
  NOT?: Prisma.ServiceAccountBackendRoleBindingScalarWhereInput | Prisma.ServiceAccountBackendRoleBindingScalarWhereInput[]
  roleId?: Prisma.StringFilter<"ServiceAccountBackendRoleBinding"> | string
  serviceAccountId?: Prisma.StringFilter<"ServiceAccountBackendRoleBinding"> | string
  createdAt?: Prisma.DateTimeFilter<"ServiceAccountBackendRoleBinding"> | Date | string
}

export type ServiceAccountBackendRoleBindingCreateWithoutServiceAccountInput = {
  createdAt?: Date | string
  role: Prisma.BackendRoleCreateNestedOneWithoutServiceAccountBindingsInput
}

export type ServiceAccountBackendRoleBindingUncheckedCreateWithoutServiceAccountInput = {
  roleId: string
  createdAt?: Date | string
}

export type ServiceAccountBackendRoleBindingCreateOrConnectWithoutServiceAccountInput = {
  where: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutServiceAccountInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutServiceAccountInput>
}

export type ServiceAccountBackendRoleBindingCreateManyServiceAccountInputEnvelope = {
  data: Prisma.ServiceAccountBackendRoleBindingCreateManyServiceAccountInput | Prisma.ServiceAccountBackendRoleBindingCreateManyServiceAccountInput[]
  skipDuplicates?: boolean
}

export type ServiceAccountBackendRoleBindingUpsertWithWhereUniqueWithoutServiceAccountInput = {
  where: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
  update: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingUpdateWithoutServiceAccountInput, Prisma.ServiceAccountBackendRoleBindingUncheckedUpdateWithoutServiceAccountInput>
  create: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateWithoutServiceAccountInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateWithoutServiceAccountInput>
}

export type ServiceAccountBackendRoleBindingUpdateWithWhereUniqueWithoutServiceAccountInput = {
  where: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
  data: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingUpdateWithoutServiceAccountInput, Prisma.ServiceAccountBackendRoleBindingUncheckedUpdateWithoutServiceAccountInput>
}

export type ServiceAccountBackendRoleBindingUpdateManyWithWhereWithoutServiceAccountInput = {
  where: Prisma.ServiceAccountBackendRoleBindingScalarWhereInput
  data: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingUpdateManyMutationInput, Prisma.ServiceAccountBackendRoleBindingUncheckedUpdateManyWithoutServiceAccountInput>
}

export type ServiceAccountBackendRoleBindingCreateManyRoleInput = {
  serviceAccountId: string
  createdAt?: Date | string
}

export type ServiceAccountBackendRoleBindingUpdateWithoutRoleInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  serviceAccount?: Prisma.BackendServiceAccountUpdateOneRequiredWithoutRoleBindingsNestedInput
}

export type ServiceAccountBackendRoleBindingUncheckedUpdateWithoutRoleInput = {
  serviceAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceAccountBackendRoleBindingUncheckedUpdateManyWithoutRoleInput = {
  serviceAccountId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceAccountBackendRoleBindingCreateManyServiceAccountInput = {
  roleId: string
  createdAt?: Date | string
}

export type ServiceAccountBackendRoleBindingUpdateWithoutServiceAccountInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.BackendRoleUpdateOneRequiredWithoutServiceAccountBindingsNestedInput
}

export type ServiceAccountBackendRoleBindingUncheckedUpdateWithoutServiceAccountInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceAccountBackendRoleBindingUncheckedUpdateManyWithoutServiceAccountInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ServiceAccountBackendRoleBindingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  roleId?: boolean
  serviceAccountId?: boolean
  createdAt?: boolean
  role?: boolean | Prisma.BackendRoleDefaultArgs<ExtArgs>
  serviceAccount?: boolean | Prisma.BackendServiceAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceAccountBackendRoleBinding"]>

export type ServiceAccountBackendRoleBindingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  roleId?: boolean
  serviceAccountId?: boolean
  createdAt?: boolean
  role?: boolean | Prisma.BackendRoleDefaultArgs<ExtArgs>
  serviceAccount?: boolean | Prisma.BackendServiceAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceAccountBackendRoleBinding"]>

export type ServiceAccountBackendRoleBindingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  roleId?: boolean
  serviceAccountId?: boolean
  createdAt?: boolean
  role?: boolean | Prisma.BackendRoleDefaultArgs<ExtArgs>
  serviceAccount?: boolean | Prisma.BackendServiceAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceAccountBackendRoleBinding"]>

export type ServiceAccountBackendRoleBindingSelectScalar = {
  roleId?: boolean
  serviceAccountId?: boolean
  createdAt?: boolean
}

export type ServiceAccountBackendRoleBindingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"roleId" | "serviceAccountId" | "createdAt", ExtArgs["result"]["serviceAccountBackendRoleBinding"]>
export type ServiceAccountBackendRoleBindingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.BackendRoleDefaultArgs<ExtArgs>
  serviceAccount?: boolean | Prisma.BackendServiceAccountDefaultArgs<ExtArgs>
}
export type ServiceAccountBackendRoleBindingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.BackendRoleDefaultArgs<ExtArgs>
  serviceAccount?: boolean | Prisma.BackendServiceAccountDefaultArgs<ExtArgs>
}
export type ServiceAccountBackendRoleBindingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.BackendRoleDefaultArgs<ExtArgs>
  serviceAccount?: boolean | Prisma.BackendServiceAccountDefaultArgs<ExtArgs>
}

export type $ServiceAccountBackendRoleBindingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServiceAccountBackendRoleBinding"
  objects: {
    /**
     * The granted backend role.
     */
    role: Prisma.$BackendRolePayload<ExtArgs>
    /**
     * The backend service account receiving the role.
     */
    serviceAccount: Prisma.$BackendServiceAccountPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    /**
     * The ID of the granted backend role.
     */
    roleId: string
    /**
     * The ID of the backend service account receiving the role.
     */
    serviceAccountId: string
    /**
     * The time when the backend role binding was created.
     */
    createdAt: Date
  }, ExtArgs["result"]["serviceAccountBackendRoleBinding"]>
  composites: {}
}

export type ServiceAccountBackendRoleBindingGetPayload<S extends boolean | null | undefined | ServiceAccountBackendRoleBindingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload, S>

export type ServiceAccountBackendRoleBindingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServiceAccountBackendRoleBindingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceAccountBackendRoleBindingCountAggregateInputType | true
  }

export interface ServiceAccountBackendRoleBindingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServiceAccountBackendRoleBinding'], meta: { name: 'ServiceAccountBackendRoleBinding' } }
  /**
   * Find zero or one ServiceAccountBackendRoleBinding that matches the filter.
   * @param {ServiceAccountBackendRoleBindingFindUniqueArgs} args - Arguments to find a ServiceAccountBackendRoleBinding
   * @example
   * // Get one ServiceAccountBackendRoleBinding
   * const serviceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServiceAccountBackendRoleBindingFindUniqueArgs>(args: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountBackendRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServiceAccountBackendRoleBinding that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServiceAccountBackendRoleBindingFindUniqueOrThrowArgs} args - Arguments to find a ServiceAccountBackendRoleBinding
   * @example
   * // Get one ServiceAccountBackendRoleBinding
   * const serviceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServiceAccountBackendRoleBindingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountBackendRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceAccountBackendRoleBinding that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountBackendRoleBindingFindFirstArgs} args - Arguments to find a ServiceAccountBackendRoleBinding
   * @example
   * // Get one ServiceAccountBackendRoleBinding
   * const serviceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServiceAccountBackendRoleBindingFindFirstArgs>(args?: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountBackendRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceAccountBackendRoleBinding that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountBackendRoleBindingFindFirstOrThrowArgs} args - Arguments to find a ServiceAccountBackendRoleBinding
   * @example
   * // Get one ServiceAccountBackendRoleBinding
   * const serviceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServiceAccountBackendRoleBindingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountBackendRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServiceAccountBackendRoleBindings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountBackendRoleBindingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServiceAccountBackendRoleBindings
   * const serviceAccountBackendRoleBindings = await prisma.serviceAccountBackendRoleBinding.findMany()
   * 
   * // Get first 10 ServiceAccountBackendRoleBindings
   * const serviceAccountBackendRoleBindings = await prisma.serviceAccountBackendRoleBinding.findMany({ take: 10 })
   * 
   * // Only select the `roleId`
   * const serviceAccountBackendRoleBindingWithRoleIdOnly = await prisma.serviceAccountBackendRoleBinding.findMany({ select: { roleId: true } })
   * 
   */
  findMany<T extends ServiceAccountBackendRoleBindingFindManyArgs>(args?: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServiceAccountBackendRoleBinding.
   * @param {ServiceAccountBackendRoleBindingCreateArgs} args - Arguments to create a ServiceAccountBackendRoleBinding.
   * @example
   * // Create one ServiceAccountBackendRoleBinding
   * const ServiceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.create({
   *   data: {
   *     // ... data to create a ServiceAccountBackendRoleBinding
   *   }
   * })
   * 
   */
  create<T extends ServiceAccountBackendRoleBindingCreateArgs>(args: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingCreateArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountBackendRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServiceAccountBackendRoleBindings.
   * @param {ServiceAccountBackendRoleBindingCreateManyArgs} args - Arguments to create many ServiceAccountBackendRoleBindings.
   * @example
   * // Create many ServiceAccountBackendRoleBindings
   * const serviceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServiceAccountBackendRoleBindingCreateManyArgs>(args?: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ServiceAccountBackendRoleBindings and returns the data saved in the database.
   * @param {ServiceAccountBackendRoleBindingCreateManyAndReturnArgs} args - Arguments to create many ServiceAccountBackendRoleBindings.
   * @example
   * // Create many ServiceAccountBackendRoleBindings
   * const serviceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ServiceAccountBackendRoleBindings and only return the `roleId`
   * const serviceAccountBackendRoleBindingWithRoleIdOnly = await prisma.serviceAccountBackendRoleBinding.createManyAndReturn({
   *   select: { roleId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ServiceAccountBackendRoleBindingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ServiceAccountBackendRoleBinding.
   * @param {ServiceAccountBackendRoleBindingDeleteArgs} args - Arguments to delete one ServiceAccountBackendRoleBinding.
   * @example
   * // Delete one ServiceAccountBackendRoleBinding
   * const ServiceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.delete({
   *   where: {
   *     // ... filter to delete one ServiceAccountBackendRoleBinding
   *   }
   * })
   * 
   */
  delete<T extends ServiceAccountBackendRoleBindingDeleteArgs>(args: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingDeleteArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountBackendRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServiceAccountBackendRoleBinding.
   * @param {ServiceAccountBackendRoleBindingUpdateArgs} args - Arguments to update one ServiceAccountBackendRoleBinding.
   * @example
   * // Update one ServiceAccountBackendRoleBinding
   * const serviceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServiceAccountBackendRoleBindingUpdateArgs>(args: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingUpdateArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountBackendRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServiceAccountBackendRoleBindings.
   * @param {ServiceAccountBackendRoleBindingDeleteManyArgs} args - Arguments to filter ServiceAccountBackendRoleBindings to delete.
   * @example
   * // Delete a few ServiceAccountBackendRoleBindings
   * const { count } = await prisma.serviceAccountBackendRoleBinding.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServiceAccountBackendRoleBindingDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceAccountBackendRoleBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountBackendRoleBindingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServiceAccountBackendRoleBindings
   * const serviceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServiceAccountBackendRoleBindingUpdateManyArgs>(args: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceAccountBackendRoleBindings and returns the data updated in the database.
   * @param {ServiceAccountBackendRoleBindingUpdateManyAndReturnArgs} args - Arguments to update many ServiceAccountBackendRoleBindings.
   * @example
   * // Update many ServiceAccountBackendRoleBindings
   * const serviceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ServiceAccountBackendRoleBindings and only return the `roleId`
   * const serviceAccountBackendRoleBindingWithRoleIdOnly = await prisma.serviceAccountBackendRoleBinding.updateManyAndReturn({
   *   select: { roleId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ServiceAccountBackendRoleBindingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ServiceAccountBackendRoleBinding.
   * @param {ServiceAccountBackendRoleBindingUpsertArgs} args - Arguments to update or create a ServiceAccountBackendRoleBinding.
   * @example
   * // Update or create a ServiceAccountBackendRoleBinding
   * const serviceAccountBackendRoleBinding = await prisma.serviceAccountBackendRoleBinding.upsert({
   *   create: {
   *     // ... data to create a ServiceAccountBackendRoleBinding
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServiceAccountBackendRoleBinding we want to update
   *   }
   * })
   */
  upsert<T extends ServiceAccountBackendRoleBindingUpsertArgs>(args: Prisma.SelectSubset<T, ServiceAccountBackendRoleBindingUpsertArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountBackendRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountBackendRoleBindingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServiceAccountBackendRoleBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountBackendRoleBindingCountArgs} args - Arguments to filter ServiceAccountBackendRoleBindings to count.
   * @example
   * // Count the number of ServiceAccountBackendRoleBindings
   * const count = await prisma.serviceAccountBackendRoleBinding.count({
   *   where: {
   *     // ... the filter for the ServiceAccountBackendRoleBindings we want to count
   *   }
   * })
  **/
  count<T extends ServiceAccountBackendRoleBindingCountArgs>(
    args?: Prisma.Subset<T, ServiceAccountBackendRoleBindingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceAccountBackendRoleBindingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServiceAccountBackendRoleBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountBackendRoleBindingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceAccountBackendRoleBindingAggregateArgs>(args: Prisma.Subset<T, ServiceAccountBackendRoleBindingAggregateArgs>): Prisma.PrismaPromise<GetServiceAccountBackendRoleBindingAggregateType<T>>

  /**
   * Group by ServiceAccountBackendRoleBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountBackendRoleBindingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServiceAccountBackendRoleBindingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServiceAccountBackendRoleBindingGroupByArgs['orderBy'] }
      : { orderBy?: ServiceAccountBackendRoleBindingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServiceAccountBackendRoleBindingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceAccountBackendRoleBindingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServiceAccountBackendRoleBinding model
 */
readonly fields: ServiceAccountBackendRoleBindingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServiceAccountBackendRoleBinding.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServiceAccountBackendRoleBindingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  role<T extends Prisma.BackendRoleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BackendRoleDefaultArgs<ExtArgs>>): Prisma.Prisma__BackendRoleClient<runtime.Types.Result.GetResult<Prisma.$BackendRolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  serviceAccount<T extends Prisma.BackendServiceAccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BackendServiceAccountDefaultArgs<ExtArgs>>): Prisma.Prisma__BackendServiceAccountClient<runtime.Types.Result.GetResult<Prisma.$BackendServiceAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServiceAccountBackendRoleBinding model
 */
export interface ServiceAccountBackendRoleBindingFieldRefs {
  readonly roleId: Prisma.FieldRef<"ServiceAccountBackendRoleBinding", 'String'>
  readonly serviceAccountId: Prisma.FieldRef<"ServiceAccountBackendRoleBinding", 'String'>
  readonly createdAt: Prisma.FieldRef<"ServiceAccountBackendRoleBinding", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ServiceAccountBackendRoleBinding findUnique
 */
export type ServiceAccountBackendRoleBindingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which ServiceAccountBackendRoleBinding to fetch.
   */
  where: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
}

/**
 * ServiceAccountBackendRoleBinding findUniqueOrThrow
 */
export type ServiceAccountBackendRoleBindingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which ServiceAccountBackendRoleBinding to fetch.
   */
  where: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
}

/**
 * ServiceAccountBackendRoleBinding findFirst
 */
export type ServiceAccountBackendRoleBindingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which ServiceAccountBackendRoleBinding to fetch.
   */
  where?: Prisma.ServiceAccountBackendRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceAccountBackendRoleBindings to fetch.
   */
  orderBy?: Prisma.ServiceAccountBackendRoleBindingOrderByWithRelationInput | Prisma.ServiceAccountBackendRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceAccountBackendRoleBindings.
   */
  cursor?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceAccountBackendRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceAccountBackendRoleBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceAccountBackendRoleBindings.
   */
  distinct?: Prisma.ServiceAccountBackendRoleBindingScalarFieldEnum | Prisma.ServiceAccountBackendRoleBindingScalarFieldEnum[]
}

/**
 * ServiceAccountBackendRoleBinding findFirstOrThrow
 */
export type ServiceAccountBackendRoleBindingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which ServiceAccountBackendRoleBinding to fetch.
   */
  where?: Prisma.ServiceAccountBackendRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceAccountBackendRoleBindings to fetch.
   */
  orderBy?: Prisma.ServiceAccountBackendRoleBindingOrderByWithRelationInput | Prisma.ServiceAccountBackendRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceAccountBackendRoleBindings.
   */
  cursor?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceAccountBackendRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceAccountBackendRoleBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceAccountBackendRoleBindings.
   */
  distinct?: Prisma.ServiceAccountBackendRoleBindingScalarFieldEnum | Prisma.ServiceAccountBackendRoleBindingScalarFieldEnum[]
}

/**
 * ServiceAccountBackendRoleBinding findMany
 */
export type ServiceAccountBackendRoleBindingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which ServiceAccountBackendRoleBindings to fetch.
   */
  where?: Prisma.ServiceAccountBackendRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceAccountBackendRoleBindings to fetch.
   */
  orderBy?: Prisma.ServiceAccountBackendRoleBindingOrderByWithRelationInput | Prisma.ServiceAccountBackendRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServiceAccountBackendRoleBindings.
   */
  cursor?: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceAccountBackendRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceAccountBackendRoleBindings.
   */
  skip?: number
  distinct?: Prisma.ServiceAccountBackendRoleBindingScalarFieldEnum | Prisma.ServiceAccountBackendRoleBindingScalarFieldEnum[]
}

/**
 * ServiceAccountBackendRoleBinding create
 */
export type ServiceAccountBackendRoleBindingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingInclude<ExtArgs> | null
  /**
   * The data needed to create a ServiceAccountBackendRoleBinding.
   */
  data: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateInput>
}

/**
 * ServiceAccountBackendRoleBinding createMany
 */
export type ServiceAccountBackendRoleBindingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServiceAccountBackendRoleBindings.
   */
  data: Prisma.ServiceAccountBackendRoleBindingCreateManyInput | Prisma.ServiceAccountBackendRoleBindingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServiceAccountBackendRoleBinding createManyAndReturn
 */
export type ServiceAccountBackendRoleBindingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * The data used to create many ServiceAccountBackendRoleBindings.
   */
  data: Prisma.ServiceAccountBackendRoleBindingCreateManyInput | Prisma.ServiceAccountBackendRoleBindingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceAccountBackendRoleBinding update
 */
export type ServiceAccountBackendRoleBindingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingInclude<ExtArgs> | null
  /**
   * The data needed to update a ServiceAccountBackendRoleBinding.
   */
  data: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingUpdateInput, Prisma.ServiceAccountBackendRoleBindingUncheckedUpdateInput>
  /**
   * Choose, which ServiceAccountBackendRoleBinding to update.
   */
  where: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
}

/**
 * ServiceAccountBackendRoleBinding updateMany
 */
export type ServiceAccountBackendRoleBindingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServiceAccountBackendRoleBindings.
   */
  data: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingUpdateManyMutationInput, Prisma.ServiceAccountBackendRoleBindingUncheckedUpdateManyInput>
  /**
   * Filter which ServiceAccountBackendRoleBindings to update
   */
  where?: Prisma.ServiceAccountBackendRoleBindingWhereInput
  /**
   * Limit how many ServiceAccountBackendRoleBindings to update.
   */
  limit?: number
}

/**
 * ServiceAccountBackendRoleBinding updateManyAndReturn
 */
export type ServiceAccountBackendRoleBindingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * The data used to update ServiceAccountBackendRoleBindings.
   */
  data: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingUpdateManyMutationInput, Prisma.ServiceAccountBackendRoleBindingUncheckedUpdateManyInput>
  /**
   * Filter which ServiceAccountBackendRoleBindings to update
   */
  where?: Prisma.ServiceAccountBackendRoleBindingWhereInput
  /**
   * Limit how many ServiceAccountBackendRoleBindings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceAccountBackendRoleBinding upsert
 */
export type ServiceAccountBackendRoleBindingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingInclude<ExtArgs> | null
  /**
   * The filter to search for the ServiceAccountBackendRoleBinding to update in case it exists.
   */
  where: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
  /**
   * In case the ServiceAccountBackendRoleBinding found by the `where` argument doesn't exist, create a new ServiceAccountBackendRoleBinding with this data.
   */
  create: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingCreateInput, Prisma.ServiceAccountBackendRoleBindingUncheckedCreateInput>
  /**
   * In case the ServiceAccountBackendRoleBinding was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServiceAccountBackendRoleBindingUpdateInput, Prisma.ServiceAccountBackendRoleBindingUncheckedUpdateInput>
}

/**
 * ServiceAccountBackendRoleBinding delete
 */
export type ServiceAccountBackendRoleBindingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingInclude<ExtArgs> | null
  /**
   * Filter which ServiceAccountBackendRoleBinding to delete.
   */
  where: Prisma.ServiceAccountBackendRoleBindingWhereUniqueInput
}

/**
 * ServiceAccountBackendRoleBinding deleteMany
 */
export type ServiceAccountBackendRoleBindingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceAccountBackendRoleBindings to delete
   */
  where?: Prisma.ServiceAccountBackendRoleBindingWhereInput
  /**
   * Limit how many ServiceAccountBackendRoleBindings to delete.
   */
  limit?: number
}

/**
 * ServiceAccountBackendRoleBinding without action
 */
export type ServiceAccountBackendRoleBindingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountBackendRoleBinding
   */
  select?: Prisma.ServiceAccountBackendRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccountBackendRoleBinding
   */
  omit?: Prisma.ServiceAccountBackendRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountBackendRoleBindingInclude<ExtArgs> | null
}
