
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserRoleBinding` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg.ts';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UserRoleBinding
 * A user role binding grants a project role to a user.
 */
export type UserRoleBindingModel = runtime.Types.Result.DefaultSelection<Prisma.$UserRoleBindingPayload>

export type AggregateUserRoleBinding = {
  _count: UserRoleBindingCountAggregateOutputType | null
  _min: UserRoleBindingMinAggregateOutputType | null
  _max: UserRoleBindingMaxAggregateOutputType | null
}

export type UserRoleBindingMinAggregateOutputType = {
  roleId: string | null
  userId: string | null
  createdAt: Date | null
}

export type UserRoleBindingMaxAggregateOutputType = {
  roleId: string | null
  userId: string | null
  createdAt: Date | null
}

export type UserRoleBindingCountAggregateOutputType = {
  roleId: number
  userId: number
  createdAt: number
  _all: number
}


export type UserRoleBindingMinAggregateInputType = {
  roleId?: true
  userId?: true
  createdAt?: true
}

export type UserRoleBindingMaxAggregateInputType = {
  roleId?: true
  userId?: true
  createdAt?: true
}

export type UserRoleBindingCountAggregateInputType = {
  roleId?: true
  userId?: true
  createdAt?: true
  _all?: true
}

export type UserRoleBindingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserRoleBinding to aggregate.
   */
  where?: Prisma.UserRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRoleBindings to fetch.
   */
  orderBy?: Prisma.UserRoleBindingOrderByWithRelationInput | Prisma.UserRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRoleBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserRoleBindings
  **/
  _count?: true | UserRoleBindingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserRoleBindingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserRoleBindingMaxAggregateInputType
}

export type GetUserRoleBindingAggregateType<T extends UserRoleBindingAggregateArgs> = {
      [P in keyof T & keyof AggregateUserRoleBinding]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserRoleBinding[P]>
    : Prisma.GetScalarType<T[P], AggregateUserRoleBinding[P]>
}




export type UserRoleBindingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserRoleBindingWhereInput
  orderBy?: Prisma.UserRoleBindingOrderByWithAggregationInput | Prisma.UserRoleBindingOrderByWithAggregationInput[]
  by: Prisma.UserRoleBindingScalarFieldEnum[] | Prisma.UserRoleBindingScalarFieldEnum
  having?: Prisma.UserRoleBindingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserRoleBindingCountAggregateInputType | true
  _min?: UserRoleBindingMinAggregateInputType
  _max?: UserRoleBindingMaxAggregateInputType
}

export type UserRoleBindingGroupByOutputType = {
  roleId: string
  userId: string
  createdAt: Date
  _count: UserRoleBindingCountAggregateOutputType | null
  _min: UserRoleBindingMinAggregateOutputType | null
  _max: UserRoleBindingMaxAggregateOutputType | null
}

type GetUserRoleBindingGroupByPayload<T extends UserRoleBindingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserRoleBindingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserRoleBindingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserRoleBindingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserRoleBindingGroupByOutputType[P]>
      }
    >
  >



export type UserRoleBindingWhereInput = {
  AND?: Prisma.UserRoleBindingWhereInput | Prisma.UserRoleBindingWhereInput[]
  OR?: Prisma.UserRoleBindingWhereInput[]
  NOT?: Prisma.UserRoleBindingWhereInput | Prisma.UserRoleBindingWhereInput[]
  roleId?: Prisma.StringFilter<"UserRoleBinding"> | string
  userId?: Prisma.StringFilter<"UserRoleBinding"> | string
  createdAt?: Prisma.DateTimeFilter<"UserRoleBinding"> | Date | string
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserRoleBindingOrderByWithRelationInput = {
  roleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  role?: Prisma.RoleOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserRoleBindingWhereUniqueInput = Prisma.AtLeast<{
  roleId_userId?: Prisma.UserRoleBindingRoleIdUserIdCompoundUniqueInput
  AND?: Prisma.UserRoleBindingWhereInput | Prisma.UserRoleBindingWhereInput[]
  OR?: Prisma.UserRoleBindingWhereInput[]
  NOT?: Prisma.UserRoleBindingWhereInput | Prisma.UserRoleBindingWhereInput[]
  roleId?: Prisma.StringFilter<"UserRoleBinding"> | string
  userId?: Prisma.StringFilter<"UserRoleBinding"> | string
  createdAt?: Prisma.DateTimeFilter<"UserRoleBinding"> | Date | string
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "roleId_userId">

export type UserRoleBindingOrderByWithAggregationInput = {
  roleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.UserRoleBindingCountOrderByAggregateInput
  _max?: Prisma.UserRoleBindingMaxOrderByAggregateInput
  _min?: Prisma.UserRoleBindingMinOrderByAggregateInput
}

export type UserRoleBindingScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserRoleBindingScalarWhereWithAggregatesInput | Prisma.UserRoleBindingScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserRoleBindingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserRoleBindingScalarWhereWithAggregatesInput | Prisma.UserRoleBindingScalarWhereWithAggregatesInput[]
  roleId?: Prisma.StringWithAggregatesFilter<"UserRoleBinding"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UserRoleBinding"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserRoleBinding"> | Date | string
}

export type UserRoleBindingCreateInput = {
  createdAt?: Date | string
  role: Prisma.RoleCreateNestedOneWithoutUserBindingsInput
  user: Prisma.UserCreateNestedOneWithoutRoleBindingsInput
}

export type UserRoleBindingUncheckedCreateInput = {
  roleId: string
  userId: string
  createdAt?: Date | string
}

export type UserRoleBindingUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.RoleUpdateOneRequiredWithoutUserBindingsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutRoleBindingsNestedInput
}

export type UserRoleBindingUncheckedUpdateInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserRoleBindingCreateManyInput = {
  roleId: string
  userId: string
  createdAt?: Date | string
}

export type UserRoleBindingUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserRoleBindingUncheckedUpdateManyInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserRoleBindingListRelationFilter = {
  every?: Prisma.UserRoleBindingWhereInput
  some?: Prisma.UserRoleBindingWhereInput
  none?: Prisma.UserRoleBindingWhereInput
}

export type UserRoleBindingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserRoleBindingRoleIdUserIdCompoundUniqueInput = {
  roleId: string
  userId: string
}

export type UserRoleBindingCountOrderByAggregateInput = {
  roleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserRoleBindingMaxOrderByAggregateInput = {
  roleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserRoleBindingMinOrderByAggregateInput = {
  roleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserRoleBindingCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutRoleInput, Prisma.UserRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.UserRoleBindingCreateWithoutRoleInput[] | Prisma.UserRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserRoleBindingCreateOrConnectWithoutRoleInput | Prisma.UserRoleBindingCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.UserRoleBindingCreateManyRoleInputEnvelope
  connect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
}

export type UserRoleBindingUncheckedCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutRoleInput, Prisma.UserRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.UserRoleBindingCreateWithoutRoleInput[] | Prisma.UserRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserRoleBindingCreateOrConnectWithoutRoleInput | Prisma.UserRoleBindingCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.UserRoleBindingCreateManyRoleInputEnvelope
  connect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
}

export type UserRoleBindingUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutRoleInput, Prisma.UserRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.UserRoleBindingCreateWithoutRoleInput[] | Prisma.UserRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserRoleBindingCreateOrConnectWithoutRoleInput | Prisma.UserRoleBindingCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.UserRoleBindingUpsertWithWhereUniqueWithoutRoleInput | Prisma.UserRoleBindingUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.UserRoleBindingCreateManyRoleInputEnvelope
  set?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  delete?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  connect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  update?: Prisma.UserRoleBindingUpdateWithWhereUniqueWithoutRoleInput | Prisma.UserRoleBindingUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.UserRoleBindingUpdateManyWithWhereWithoutRoleInput | Prisma.UserRoleBindingUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.UserRoleBindingScalarWhereInput | Prisma.UserRoleBindingScalarWhereInput[]
}

export type UserRoleBindingUncheckedUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutRoleInput, Prisma.UserRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.UserRoleBindingCreateWithoutRoleInput[] | Prisma.UserRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserRoleBindingCreateOrConnectWithoutRoleInput | Prisma.UserRoleBindingCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.UserRoleBindingUpsertWithWhereUniqueWithoutRoleInput | Prisma.UserRoleBindingUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.UserRoleBindingCreateManyRoleInputEnvelope
  set?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  delete?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  connect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  update?: Prisma.UserRoleBindingUpdateWithWhereUniqueWithoutRoleInput | Prisma.UserRoleBindingUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.UserRoleBindingUpdateManyWithWhereWithoutRoleInput | Prisma.UserRoleBindingUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.UserRoleBindingScalarWhereInput | Prisma.UserRoleBindingScalarWhereInput[]
}

export type UserRoleBindingCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutUserInput, Prisma.UserRoleBindingUncheckedCreateWithoutUserInput> | Prisma.UserRoleBindingCreateWithoutUserInput[] | Prisma.UserRoleBindingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserRoleBindingCreateOrConnectWithoutUserInput | Prisma.UserRoleBindingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserRoleBindingCreateManyUserInputEnvelope
  connect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
}

export type UserRoleBindingUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutUserInput, Prisma.UserRoleBindingUncheckedCreateWithoutUserInput> | Prisma.UserRoleBindingCreateWithoutUserInput[] | Prisma.UserRoleBindingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserRoleBindingCreateOrConnectWithoutUserInput | Prisma.UserRoleBindingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserRoleBindingCreateManyUserInputEnvelope
  connect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
}

export type UserRoleBindingUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutUserInput, Prisma.UserRoleBindingUncheckedCreateWithoutUserInput> | Prisma.UserRoleBindingCreateWithoutUserInput[] | Prisma.UserRoleBindingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserRoleBindingCreateOrConnectWithoutUserInput | Prisma.UserRoleBindingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserRoleBindingUpsertWithWhereUniqueWithoutUserInput | Prisma.UserRoleBindingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserRoleBindingCreateManyUserInputEnvelope
  set?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  delete?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  connect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  update?: Prisma.UserRoleBindingUpdateWithWhereUniqueWithoutUserInput | Prisma.UserRoleBindingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserRoleBindingUpdateManyWithWhereWithoutUserInput | Prisma.UserRoleBindingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserRoleBindingScalarWhereInput | Prisma.UserRoleBindingScalarWhereInput[]
}

export type UserRoleBindingUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutUserInput, Prisma.UserRoleBindingUncheckedCreateWithoutUserInput> | Prisma.UserRoleBindingCreateWithoutUserInput[] | Prisma.UserRoleBindingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserRoleBindingCreateOrConnectWithoutUserInput | Prisma.UserRoleBindingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserRoleBindingUpsertWithWhereUniqueWithoutUserInput | Prisma.UserRoleBindingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserRoleBindingCreateManyUserInputEnvelope
  set?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  delete?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  connect?: Prisma.UserRoleBindingWhereUniqueInput | Prisma.UserRoleBindingWhereUniqueInput[]
  update?: Prisma.UserRoleBindingUpdateWithWhereUniqueWithoutUserInput | Prisma.UserRoleBindingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserRoleBindingUpdateManyWithWhereWithoutUserInput | Prisma.UserRoleBindingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserRoleBindingScalarWhereInput | Prisma.UserRoleBindingScalarWhereInput[]
}

export type UserRoleBindingCreateWithoutRoleInput = {
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutRoleBindingsInput
}

export type UserRoleBindingUncheckedCreateWithoutRoleInput = {
  userId: string
  createdAt?: Date | string
}

export type UserRoleBindingCreateOrConnectWithoutRoleInput = {
  where: Prisma.UserRoleBindingWhereUniqueInput
  create: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutRoleInput, Prisma.UserRoleBindingUncheckedCreateWithoutRoleInput>
}

export type UserRoleBindingCreateManyRoleInputEnvelope = {
  data: Prisma.UserRoleBindingCreateManyRoleInput | Prisma.UserRoleBindingCreateManyRoleInput[]
}

export type UserRoleBindingUpsertWithWhereUniqueWithoutRoleInput = {
  where: Prisma.UserRoleBindingWhereUniqueInput
  update: Prisma.XOR<Prisma.UserRoleBindingUpdateWithoutRoleInput, Prisma.UserRoleBindingUncheckedUpdateWithoutRoleInput>
  create: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutRoleInput, Prisma.UserRoleBindingUncheckedCreateWithoutRoleInput>
}

export type UserRoleBindingUpdateWithWhereUniqueWithoutRoleInput = {
  where: Prisma.UserRoleBindingWhereUniqueInput
  data: Prisma.XOR<Prisma.UserRoleBindingUpdateWithoutRoleInput, Prisma.UserRoleBindingUncheckedUpdateWithoutRoleInput>
}

export type UserRoleBindingUpdateManyWithWhereWithoutRoleInput = {
  where: Prisma.UserRoleBindingScalarWhereInput
  data: Prisma.XOR<Prisma.UserRoleBindingUpdateManyMutationInput, Prisma.UserRoleBindingUncheckedUpdateManyWithoutRoleInput>
}

export type UserRoleBindingScalarWhereInput = {
  AND?: Prisma.UserRoleBindingScalarWhereInput | Prisma.UserRoleBindingScalarWhereInput[]
  OR?: Prisma.UserRoleBindingScalarWhereInput[]
  NOT?: Prisma.UserRoleBindingScalarWhereInput | Prisma.UserRoleBindingScalarWhereInput[]
  roleId?: Prisma.StringFilter<"UserRoleBinding"> | string
  userId?: Prisma.StringFilter<"UserRoleBinding"> | string
  createdAt?: Prisma.DateTimeFilter<"UserRoleBinding"> | Date | string
}

export type UserRoleBindingCreateWithoutUserInput = {
  createdAt?: Date | string
  role: Prisma.RoleCreateNestedOneWithoutUserBindingsInput
}

export type UserRoleBindingUncheckedCreateWithoutUserInput = {
  roleId: string
  createdAt?: Date | string
}

export type UserRoleBindingCreateOrConnectWithoutUserInput = {
  where: Prisma.UserRoleBindingWhereUniqueInput
  create: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutUserInput, Prisma.UserRoleBindingUncheckedCreateWithoutUserInput>
}

export type UserRoleBindingCreateManyUserInputEnvelope = {
  data: Prisma.UserRoleBindingCreateManyUserInput | Prisma.UserRoleBindingCreateManyUserInput[]
}

export type UserRoleBindingUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserRoleBindingWhereUniqueInput
  update: Prisma.XOR<Prisma.UserRoleBindingUpdateWithoutUserInput, Prisma.UserRoleBindingUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserRoleBindingCreateWithoutUserInput, Prisma.UserRoleBindingUncheckedCreateWithoutUserInput>
}

export type UserRoleBindingUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserRoleBindingWhereUniqueInput
  data: Prisma.XOR<Prisma.UserRoleBindingUpdateWithoutUserInput, Prisma.UserRoleBindingUncheckedUpdateWithoutUserInput>
}

export type UserRoleBindingUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserRoleBindingScalarWhereInput
  data: Prisma.XOR<Prisma.UserRoleBindingUpdateManyMutationInput, Prisma.UserRoleBindingUncheckedUpdateManyWithoutUserInput>
}

export type UserRoleBindingCreateManyRoleInput = {
  userId: string
  createdAt?: Date | string
}

export type UserRoleBindingUpdateWithoutRoleInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutRoleBindingsNestedInput
}

export type UserRoleBindingUncheckedUpdateWithoutRoleInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserRoleBindingUncheckedUpdateManyWithoutRoleInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserRoleBindingCreateManyUserInput = {
  roleId: string
  createdAt?: Date | string
}

export type UserRoleBindingUpdateWithoutUserInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.RoleUpdateOneRequiredWithoutUserBindingsNestedInput
}

export type UserRoleBindingUncheckedUpdateWithoutUserInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserRoleBindingUncheckedUpdateManyWithoutUserInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserRoleBindingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  roleId?: boolean
  userId?: boolean
  createdAt?: boolean
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userRoleBinding"]>

export type UserRoleBindingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  roleId?: boolean
  userId?: boolean
  createdAt?: boolean
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userRoleBinding"]>

export type UserRoleBindingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  roleId?: boolean
  userId?: boolean
  createdAt?: boolean
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userRoleBinding"]>

export type UserRoleBindingSelectScalar = {
  roleId?: boolean
  userId?: boolean
  createdAt?: boolean
}

export type UserRoleBindingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"roleId" | "userId" | "createdAt", ExtArgs["result"]["userRoleBinding"]>
export type UserRoleBindingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserRoleBindingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserRoleBindingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserRoleBindingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserRoleBinding"
  objects: {
    /**
     * The granted role.
     */
    role: Prisma.$RolePayload<ExtArgs>
    /**
     * The user receiving the role.
     */
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    /**
     * The ID of the granted role.
     */
    roleId: string
    /**
     * The ID of the user receiving the role.
     */
    userId: string
    /**
     * The time when the user role binding was created.
     */
    createdAt: Date
  }, ExtArgs["result"]["userRoleBinding"]>
  composites: {}
}

export type UserRoleBindingGetPayload<S extends boolean | null | undefined | UserRoleBindingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload, S>

export type UserRoleBindingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserRoleBindingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserRoleBindingCountAggregateInputType | true
  }

export interface UserRoleBindingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserRoleBinding'], meta: { name: 'UserRoleBinding' } }
  /**
   * Find zero or one UserRoleBinding that matches the filter.
   * @param {UserRoleBindingFindUniqueArgs} args - Arguments to find a UserRoleBinding
   * @example
   * // Get one UserRoleBinding
   * const userRoleBinding = await prisma.userRoleBinding.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserRoleBindingFindUniqueArgs>(args: Prisma.SelectSubset<T, UserRoleBindingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserRoleBinding that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserRoleBindingFindUniqueOrThrowArgs} args - Arguments to find a UserRoleBinding
   * @example
   * // Get one UserRoleBinding
   * const userRoleBinding = await prisma.userRoleBinding.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserRoleBindingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserRoleBindingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserRoleBinding that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleBindingFindFirstArgs} args - Arguments to find a UserRoleBinding
   * @example
   * // Get one UserRoleBinding
   * const userRoleBinding = await prisma.userRoleBinding.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserRoleBindingFindFirstArgs>(args?: Prisma.SelectSubset<T, UserRoleBindingFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserRoleBinding that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleBindingFindFirstOrThrowArgs} args - Arguments to find a UserRoleBinding
   * @example
   * // Get one UserRoleBinding
   * const userRoleBinding = await prisma.userRoleBinding.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserRoleBindingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserRoleBindingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserRoleBindings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleBindingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserRoleBindings
   * const userRoleBindings = await prisma.userRoleBinding.findMany()
   * 
   * // Get first 10 UserRoleBindings
   * const userRoleBindings = await prisma.userRoleBinding.findMany({ take: 10 })
   * 
   * // Only select the `roleId`
   * const userRoleBindingWithRoleIdOnly = await prisma.userRoleBinding.findMany({ select: { roleId: true } })
   * 
   */
  findMany<T extends UserRoleBindingFindManyArgs>(args?: Prisma.SelectSubset<T, UserRoleBindingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserRoleBinding.
   * @param {UserRoleBindingCreateArgs} args - Arguments to create a UserRoleBinding.
   * @example
   * // Create one UserRoleBinding
   * const UserRoleBinding = await prisma.userRoleBinding.create({
   *   data: {
   *     // ... data to create a UserRoleBinding
   *   }
   * })
   * 
   */
  create<T extends UserRoleBindingCreateArgs>(args: Prisma.SelectSubset<T, UserRoleBindingCreateArgs<ExtArgs>>): Prisma.Prisma__UserRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserRoleBindings.
   * @param {UserRoleBindingCreateManyArgs} args - Arguments to create many UserRoleBindings.
   * @example
   * // Create many UserRoleBindings
   * const userRoleBinding = await prisma.userRoleBinding.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserRoleBindingCreateManyArgs>(args?: Prisma.SelectSubset<T, UserRoleBindingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserRoleBindings and returns the data saved in the database.
   * @param {UserRoleBindingCreateManyAndReturnArgs} args - Arguments to create many UserRoleBindings.
   * @example
   * // Create many UserRoleBindings
   * const userRoleBinding = await prisma.userRoleBinding.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserRoleBindings and only return the `roleId`
   * const userRoleBindingWithRoleIdOnly = await prisma.userRoleBinding.createManyAndReturn({
   *   select: { roleId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserRoleBindingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserRoleBindingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserRoleBinding.
   * @param {UserRoleBindingDeleteArgs} args - Arguments to delete one UserRoleBinding.
   * @example
   * // Delete one UserRoleBinding
   * const UserRoleBinding = await prisma.userRoleBinding.delete({
   *   where: {
   *     // ... filter to delete one UserRoleBinding
   *   }
   * })
   * 
   */
  delete<T extends UserRoleBindingDeleteArgs>(args: Prisma.SelectSubset<T, UserRoleBindingDeleteArgs<ExtArgs>>): Prisma.Prisma__UserRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserRoleBinding.
   * @param {UserRoleBindingUpdateArgs} args - Arguments to update one UserRoleBinding.
   * @example
   * // Update one UserRoleBinding
   * const userRoleBinding = await prisma.userRoleBinding.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserRoleBindingUpdateArgs>(args: Prisma.SelectSubset<T, UserRoleBindingUpdateArgs<ExtArgs>>): Prisma.Prisma__UserRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserRoleBindings.
   * @param {UserRoleBindingDeleteManyArgs} args - Arguments to filter UserRoleBindings to delete.
   * @example
   * // Delete a few UserRoleBindings
   * const { count } = await prisma.userRoleBinding.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserRoleBindingDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserRoleBindingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserRoleBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleBindingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserRoleBindings
   * const userRoleBinding = await prisma.userRoleBinding.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserRoleBindingUpdateManyArgs>(args: Prisma.SelectSubset<T, UserRoleBindingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserRoleBindings and returns the data updated in the database.
   * @param {UserRoleBindingUpdateManyAndReturnArgs} args - Arguments to update many UserRoleBindings.
   * @example
   * // Update many UserRoleBindings
   * const userRoleBinding = await prisma.userRoleBinding.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserRoleBindings and only return the `roleId`
   * const userRoleBindingWithRoleIdOnly = await prisma.userRoleBinding.updateManyAndReturn({
   *   select: { roleId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserRoleBindingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserRoleBindingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserRoleBinding.
   * @param {UserRoleBindingUpsertArgs} args - Arguments to update or create a UserRoleBinding.
   * @example
   * // Update or create a UserRoleBinding
   * const userRoleBinding = await prisma.userRoleBinding.upsert({
   *   create: {
   *     // ... data to create a UserRoleBinding
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserRoleBinding we want to update
   *   }
   * })
   */
  upsert<T extends UserRoleBindingUpsertArgs>(args: Prisma.SelectSubset<T, UserRoleBindingUpsertArgs<ExtArgs>>): Prisma.Prisma__UserRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserRoleBindingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserRoleBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleBindingCountArgs} args - Arguments to filter UserRoleBindings to count.
   * @example
   * // Count the number of UserRoleBindings
   * const count = await prisma.userRoleBinding.count({
   *   where: {
   *     // ... the filter for the UserRoleBindings we want to count
   *   }
   * })
  **/
  count<T extends UserRoleBindingCountArgs>(
    args?: Prisma.Subset<T, UserRoleBindingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserRoleBindingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserRoleBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleBindingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserRoleBindingAggregateArgs>(args: Prisma.Subset<T, UserRoleBindingAggregateArgs>): Prisma.PrismaPromise<GetUserRoleBindingAggregateType<T>>

  /**
   * Group by UserRoleBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleBindingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserRoleBindingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserRoleBindingGroupByArgs['orderBy'] }
      : { orderBy?: UserRoleBindingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserRoleBindingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserRoleBindingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserRoleBinding model
 */
readonly fields: UserRoleBindingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserRoleBinding.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserRoleBindingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  role<T extends Prisma.RoleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoleDefaultArgs<ExtArgs>>): Prisma.Prisma__RoleClient<runtime.Types.Result.GetResult<Prisma.$RolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserRoleBinding model
 */
export interface UserRoleBindingFieldRefs {
  readonly roleId: Prisma.FieldRef<"UserRoleBinding", 'String'>
  readonly userId: Prisma.FieldRef<"UserRoleBinding", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserRoleBinding", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserRoleBinding findUnique
 */
export type UserRoleBindingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which UserRoleBinding to fetch.
   */
  where: Prisma.UserRoleBindingWhereUniqueInput
}

/**
 * UserRoleBinding findUniqueOrThrow
 */
export type UserRoleBindingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which UserRoleBinding to fetch.
   */
  where: Prisma.UserRoleBindingWhereUniqueInput
}

/**
 * UserRoleBinding findFirst
 */
export type UserRoleBindingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which UserRoleBinding to fetch.
   */
  where?: Prisma.UserRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRoleBindings to fetch.
   */
  orderBy?: Prisma.UserRoleBindingOrderByWithRelationInput | Prisma.UserRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserRoleBindings.
   */
  cursor?: Prisma.UserRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRoleBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserRoleBindings.
   */
  distinct?: Prisma.UserRoleBindingScalarFieldEnum | Prisma.UserRoleBindingScalarFieldEnum[]
}

/**
 * UserRoleBinding findFirstOrThrow
 */
export type UserRoleBindingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which UserRoleBinding to fetch.
   */
  where?: Prisma.UserRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRoleBindings to fetch.
   */
  orderBy?: Prisma.UserRoleBindingOrderByWithRelationInput | Prisma.UserRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserRoleBindings.
   */
  cursor?: Prisma.UserRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRoleBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserRoleBindings.
   */
  distinct?: Prisma.UserRoleBindingScalarFieldEnum | Prisma.UserRoleBindingScalarFieldEnum[]
}

/**
 * UserRoleBinding findMany
 */
export type UserRoleBindingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which UserRoleBindings to fetch.
   */
  where?: Prisma.UserRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRoleBindings to fetch.
   */
  orderBy?: Prisma.UserRoleBindingOrderByWithRelationInput | Prisma.UserRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserRoleBindings.
   */
  cursor?: Prisma.UserRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRoleBindings.
   */
  skip?: number
  distinct?: Prisma.UserRoleBindingScalarFieldEnum | Prisma.UserRoleBindingScalarFieldEnum[]
}

/**
 * UserRoleBinding create
 */
export type UserRoleBindingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingInclude<ExtArgs> | null
  /**
   * The data needed to create a UserRoleBinding.
   */
  data: Prisma.XOR<Prisma.UserRoleBindingCreateInput, Prisma.UserRoleBindingUncheckedCreateInput>
}

/**
 * UserRoleBinding createMany
 */
export type UserRoleBindingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserRoleBindings.
   */
  data: Prisma.UserRoleBindingCreateManyInput | Prisma.UserRoleBindingCreateManyInput[]
}

/**
 * UserRoleBinding createManyAndReturn
 */
export type UserRoleBindingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * The data used to create many UserRoleBindings.
   */
  data: Prisma.UserRoleBindingCreateManyInput | Prisma.UserRoleBindingCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserRoleBinding update
 */
export type UserRoleBindingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingInclude<ExtArgs> | null
  /**
   * The data needed to update a UserRoleBinding.
   */
  data: Prisma.XOR<Prisma.UserRoleBindingUpdateInput, Prisma.UserRoleBindingUncheckedUpdateInput>
  /**
   * Choose, which UserRoleBinding to update.
   */
  where: Prisma.UserRoleBindingWhereUniqueInput
}

/**
 * UserRoleBinding updateMany
 */
export type UserRoleBindingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserRoleBindings.
   */
  data: Prisma.XOR<Prisma.UserRoleBindingUpdateManyMutationInput, Prisma.UserRoleBindingUncheckedUpdateManyInput>
  /**
   * Filter which UserRoleBindings to update
   */
  where?: Prisma.UserRoleBindingWhereInput
  /**
   * Limit how many UserRoleBindings to update.
   */
  limit?: number
}

/**
 * UserRoleBinding updateManyAndReturn
 */
export type UserRoleBindingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * The data used to update UserRoleBindings.
   */
  data: Prisma.XOR<Prisma.UserRoleBindingUpdateManyMutationInput, Prisma.UserRoleBindingUncheckedUpdateManyInput>
  /**
   * Filter which UserRoleBindings to update
   */
  where?: Prisma.UserRoleBindingWhereInput
  /**
   * Limit how many UserRoleBindings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserRoleBinding upsert
 */
export type UserRoleBindingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingInclude<ExtArgs> | null
  /**
   * The filter to search for the UserRoleBinding to update in case it exists.
   */
  where: Prisma.UserRoleBindingWhereUniqueInput
  /**
   * In case the UserRoleBinding found by the `where` argument doesn't exist, create a new UserRoleBinding with this data.
   */
  create: Prisma.XOR<Prisma.UserRoleBindingCreateInput, Prisma.UserRoleBindingUncheckedCreateInput>
  /**
   * In case the UserRoleBinding was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserRoleBindingUpdateInput, Prisma.UserRoleBindingUncheckedUpdateInput>
}

/**
 * UserRoleBinding delete
 */
export type UserRoleBindingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingInclude<ExtArgs> | null
  /**
   * Filter which UserRoleBinding to delete.
   */
  where: Prisma.UserRoleBindingWhereUniqueInput
}

/**
 * UserRoleBinding deleteMany
 */
export type UserRoleBindingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserRoleBindings to delete
   */
  where?: Prisma.UserRoleBindingWhereInput
  /**
   * Limit how many UserRoleBindings to delete.
   */
  limit?: number
}

/**
 * UserRoleBinding without action
 */
export type UserRoleBindingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRoleBinding
   */
  select?: Prisma.UserRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRoleBinding
   */
  omit?: Prisma.UserRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleBindingInclude<ExtArgs> | null
}
