
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserGroupRoleBinding` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg.ts';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UserGroupRoleBinding
 * A user group role binding grants a project role to a backend-managed user group.
 */
export type UserGroupRoleBindingModel = runtime.Types.Result.DefaultSelection<Prisma.$UserGroupRoleBindingPayload>

export type AggregateUserGroupRoleBinding = {
  _count: UserGroupRoleBindingCountAggregateOutputType | null
  _min: UserGroupRoleBindingMinAggregateOutputType | null
  _max: UserGroupRoleBindingMaxAggregateOutputType | null
}

export type UserGroupRoleBindingMinAggregateOutputType = {
  roleId: string | null
  groupId: string | null
  createdAt: Date | null
}

export type UserGroupRoleBindingMaxAggregateOutputType = {
  roleId: string | null
  groupId: string | null
  createdAt: Date | null
}

export type UserGroupRoleBindingCountAggregateOutputType = {
  roleId: number
  groupId: number
  createdAt: number
  _all: number
}


export type UserGroupRoleBindingMinAggregateInputType = {
  roleId?: true
  groupId?: true
  createdAt?: true
}

export type UserGroupRoleBindingMaxAggregateInputType = {
  roleId?: true
  groupId?: true
  createdAt?: true
}

export type UserGroupRoleBindingCountAggregateInputType = {
  roleId?: true
  groupId?: true
  createdAt?: true
  _all?: true
}

export type UserGroupRoleBindingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserGroupRoleBinding to aggregate.
   */
  where?: Prisma.UserGroupRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserGroupRoleBindings to fetch.
   */
  orderBy?: Prisma.UserGroupRoleBindingOrderByWithRelationInput | Prisma.UserGroupRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserGroupRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserGroupRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserGroupRoleBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserGroupRoleBindings
  **/
  _count?: true | UserGroupRoleBindingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserGroupRoleBindingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserGroupRoleBindingMaxAggregateInputType
}

export type GetUserGroupRoleBindingAggregateType<T extends UserGroupRoleBindingAggregateArgs> = {
      [P in keyof T & keyof AggregateUserGroupRoleBinding]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserGroupRoleBinding[P]>
    : Prisma.GetScalarType<T[P], AggregateUserGroupRoleBinding[P]>
}




export type UserGroupRoleBindingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserGroupRoleBindingWhereInput
  orderBy?: Prisma.UserGroupRoleBindingOrderByWithAggregationInput | Prisma.UserGroupRoleBindingOrderByWithAggregationInput[]
  by: Prisma.UserGroupRoleBindingScalarFieldEnum[] | Prisma.UserGroupRoleBindingScalarFieldEnum
  having?: Prisma.UserGroupRoleBindingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserGroupRoleBindingCountAggregateInputType | true
  _min?: UserGroupRoleBindingMinAggregateInputType
  _max?: UserGroupRoleBindingMaxAggregateInputType
}

export type UserGroupRoleBindingGroupByOutputType = {
  roleId: string
  groupId: string
  createdAt: Date
  _count: UserGroupRoleBindingCountAggregateOutputType | null
  _min: UserGroupRoleBindingMinAggregateOutputType | null
  _max: UserGroupRoleBindingMaxAggregateOutputType | null
}

type GetUserGroupRoleBindingGroupByPayload<T extends UserGroupRoleBindingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupRoleBindingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupRoleBindingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupRoleBindingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupRoleBindingGroupByOutputType[P]>
      }
    >
  >



export type UserGroupRoleBindingWhereInput = {
  AND?: Prisma.UserGroupRoleBindingWhereInput | Prisma.UserGroupRoleBindingWhereInput[]
  OR?: Prisma.UserGroupRoleBindingWhereInput[]
  NOT?: Prisma.UserGroupRoleBindingWhereInput | Prisma.UserGroupRoleBindingWhereInput[]
  roleId?: Prisma.StringFilter<"UserGroupRoleBinding"> | string
  groupId?: Prisma.StringFilter<"UserGroupRoleBinding"> | string
  createdAt?: Prisma.DateTimeFilter<"UserGroupRoleBinding"> | Date | string
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput>
  group?: Prisma.XOR<Prisma.UserGroupScalarRelationFilter, Prisma.UserGroupWhereInput>
}

export type UserGroupRoleBindingOrderByWithRelationInput = {
  roleId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  role?: Prisma.RoleOrderByWithRelationInput
  group?: Prisma.UserGroupOrderByWithRelationInput
}

export type UserGroupRoleBindingWhereUniqueInput = Prisma.AtLeast<{
  roleId_groupId?: Prisma.UserGroupRoleBindingRoleIdGroupIdCompoundUniqueInput
  AND?: Prisma.UserGroupRoleBindingWhereInput | Prisma.UserGroupRoleBindingWhereInput[]
  OR?: Prisma.UserGroupRoleBindingWhereInput[]
  NOT?: Prisma.UserGroupRoleBindingWhereInput | Prisma.UserGroupRoleBindingWhereInput[]
  roleId?: Prisma.StringFilter<"UserGroupRoleBinding"> | string
  groupId?: Prisma.StringFilter<"UserGroupRoleBinding"> | string
  createdAt?: Prisma.DateTimeFilter<"UserGroupRoleBinding"> | Date | string
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput>
  group?: Prisma.XOR<Prisma.UserGroupScalarRelationFilter, Prisma.UserGroupWhereInput>
}, "roleId_groupId">

export type UserGroupRoleBindingOrderByWithAggregationInput = {
  roleId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.UserGroupRoleBindingCountOrderByAggregateInput
  _max?: Prisma.UserGroupRoleBindingMaxOrderByAggregateInput
  _min?: Prisma.UserGroupRoleBindingMinOrderByAggregateInput
}

export type UserGroupRoleBindingScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserGroupRoleBindingScalarWhereWithAggregatesInput | Prisma.UserGroupRoleBindingScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserGroupRoleBindingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserGroupRoleBindingScalarWhereWithAggregatesInput | Prisma.UserGroupRoleBindingScalarWhereWithAggregatesInput[]
  roleId?: Prisma.StringWithAggregatesFilter<"UserGroupRoleBinding"> | string
  groupId?: Prisma.StringWithAggregatesFilter<"UserGroupRoleBinding"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserGroupRoleBinding"> | Date | string
}

export type UserGroupRoleBindingCreateInput = {
  createdAt?: Date | string
  role: Prisma.RoleCreateNestedOneWithoutGroupBindingsInput
  group: Prisma.UserGroupCreateNestedOneWithoutRoleBindingsInput
}

export type UserGroupRoleBindingUncheckedCreateInput = {
  roleId: string
  groupId: string
  createdAt?: Date | string
}

export type UserGroupRoleBindingUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.RoleUpdateOneRequiredWithoutGroupBindingsNestedInput
  group?: Prisma.UserGroupUpdateOneRequiredWithoutRoleBindingsNestedInput
}

export type UserGroupRoleBindingUncheckedUpdateInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserGroupRoleBindingCreateManyInput = {
  roleId: string
  groupId: string
  createdAt?: Date | string
}

export type UserGroupRoleBindingUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserGroupRoleBindingUncheckedUpdateManyInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserGroupRoleBindingListRelationFilter = {
  every?: Prisma.UserGroupRoleBindingWhereInput
  some?: Prisma.UserGroupRoleBindingWhereInput
  none?: Prisma.UserGroupRoleBindingWhereInput
}

export type UserGroupRoleBindingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserGroupRoleBindingRoleIdGroupIdCompoundUniqueInput = {
  roleId: string
  groupId: string
}

export type UserGroupRoleBindingCountOrderByAggregateInput = {
  roleId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserGroupRoleBindingMaxOrderByAggregateInput = {
  roleId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserGroupRoleBindingMinOrderByAggregateInput = {
  roleId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserGroupRoleBindingCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutRoleInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.UserGroupRoleBindingCreateWithoutRoleInput[] | Prisma.UserGroupRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserGroupRoleBindingCreateOrConnectWithoutRoleInput | Prisma.UserGroupRoleBindingCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.UserGroupRoleBindingCreateManyRoleInputEnvelope
  connect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
}

export type UserGroupRoleBindingUncheckedCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutRoleInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.UserGroupRoleBindingCreateWithoutRoleInput[] | Prisma.UserGroupRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserGroupRoleBindingCreateOrConnectWithoutRoleInput | Prisma.UserGroupRoleBindingCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.UserGroupRoleBindingCreateManyRoleInputEnvelope
  connect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
}

export type UserGroupRoleBindingUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutRoleInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.UserGroupRoleBindingCreateWithoutRoleInput[] | Prisma.UserGroupRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserGroupRoleBindingCreateOrConnectWithoutRoleInput | Prisma.UserGroupRoleBindingCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.UserGroupRoleBindingUpsertWithWhereUniqueWithoutRoleInput | Prisma.UserGroupRoleBindingUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.UserGroupRoleBindingCreateManyRoleInputEnvelope
  set?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  delete?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  connect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  update?: Prisma.UserGroupRoleBindingUpdateWithWhereUniqueWithoutRoleInput | Prisma.UserGroupRoleBindingUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.UserGroupRoleBindingUpdateManyWithWhereWithoutRoleInput | Prisma.UserGroupRoleBindingUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.UserGroupRoleBindingScalarWhereInput | Prisma.UserGroupRoleBindingScalarWhereInput[]
}

export type UserGroupRoleBindingUncheckedUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutRoleInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutRoleInput> | Prisma.UserGroupRoleBindingCreateWithoutRoleInput[] | Prisma.UserGroupRoleBindingUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.UserGroupRoleBindingCreateOrConnectWithoutRoleInput | Prisma.UserGroupRoleBindingCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.UserGroupRoleBindingUpsertWithWhereUniqueWithoutRoleInput | Prisma.UserGroupRoleBindingUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.UserGroupRoleBindingCreateManyRoleInputEnvelope
  set?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  delete?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  connect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  update?: Prisma.UserGroupRoleBindingUpdateWithWhereUniqueWithoutRoleInput | Prisma.UserGroupRoleBindingUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.UserGroupRoleBindingUpdateManyWithWhereWithoutRoleInput | Prisma.UserGroupRoleBindingUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.UserGroupRoleBindingScalarWhereInput | Prisma.UserGroupRoleBindingScalarWhereInput[]
}

export type UserGroupRoleBindingCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutGroupInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutGroupInput> | Prisma.UserGroupRoleBindingCreateWithoutGroupInput[] | Prisma.UserGroupRoleBindingUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.UserGroupRoleBindingCreateOrConnectWithoutGroupInput | Prisma.UserGroupRoleBindingCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.UserGroupRoleBindingCreateManyGroupInputEnvelope
  connect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
}

export type UserGroupRoleBindingUncheckedCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutGroupInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutGroupInput> | Prisma.UserGroupRoleBindingCreateWithoutGroupInput[] | Prisma.UserGroupRoleBindingUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.UserGroupRoleBindingCreateOrConnectWithoutGroupInput | Prisma.UserGroupRoleBindingCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.UserGroupRoleBindingCreateManyGroupInputEnvelope
  connect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
}

export type UserGroupRoleBindingUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutGroupInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutGroupInput> | Prisma.UserGroupRoleBindingCreateWithoutGroupInput[] | Prisma.UserGroupRoleBindingUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.UserGroupRoleBindingCreateOrConnectWithoutGroupInput | Prisma.UserGroupRoleBindingCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.UserGroupRoleBindingUpsertWithWhereUniqueWithoutGroupInput | Prisma.UserGroupRoleBindingUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.UserGroupRoleBindingCreateManyGroupInputEnvelope
  set?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  delete?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  connect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  update?: Prisma.UserGroupRoleBindingUpdateWithWhereUniqueWithoutGroupInput | Prisma.UserGroupRoleBindingUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.UserGroupRoleBindingUpdateManyWithWhereWithoutGroupInput | Prisma.UserGroupRoleBindingUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.UserGroupRoleBindingScalarWhereInput | Prisma.UserGroupRoleBindingScalarWhereInput[]
}

export type UserGroupRoleBindingUncheckedUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutGroupInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutGroupInput> | Prisma.UserGroupRoleBindingCreateWithoutGroupInput[] | Prisma.UserGroupRoleBindingUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.UserGroupRoleBindingCreateOrConnectWithoutGroupInput | Prisma.UserGroupRoleBindingCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.UserGroupRoleBindingUpsertWithWhereUniqueWithoutGroupInput | Prisma.UserGroupRoleBindingUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.UserGroupRoleBindingCreateManyGroupInputEnvelope
  set?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  disconnect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  delete?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  connect?: Prisma.UserGroupRoleBindingWhereUniqueInput | Prisma.UserGroupRoleBindingWhereUniqueInput[]
  update?: Prisma.UserGroupRoleBindingUpdateWithWhereUniqueWithoutGroupInput | Prisma.UserGroupRoleBindingUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.UserGroupRoleBindingUpdateManyWithWhereWithoutGroupInput | Prisma.UserGroupRoleBindingUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.UserGroupRoleBindingScalarWhereInput | Prisma.UserGroupRoleBindingScalarWhereInput[]
}

export type UserGroupRoleBindingCreateWithoutRoleInput = {
  createdAt?: Date | string
  group: Prisma.UserGroupCreateNestedOneWithoutRoleBindingsInput
}

export type UserGroupRoleBindingUncheckedCreateWithoutRoleInput = {
  groupId: string
  createdAt?: Date | string
}

export type UserGroupRoleBindingCreateOrConnectWithoutRoleInput = {
  where: Prisma.UserGroupRoleBindingWhereUniqueInput
  create: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutRoleInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutRoleInput>
}

export type UserGroupRoleBindingCreateManyRoleInputEnvelope = {
  data: Prisma.UserGroupRoleBindingCreateManyRoleInput | Prisma.UserGroupRoleBindingCreateManyRoleInput[]
}

export type UserGroupRoleBindingUpsertWithWhereUniqueWithoutRoleInput = {
  where: Prisma.UserGroupRoleBindingWhereUniqueInput
  update: Prisma.XOR<Prisma.UserGroupRoleBindingUpdateWithoutRoleInput, Prisma.UserGroupRoleBindingUncheckedUpdateWithoutRoleInput>
  create: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutRoleInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutRoleInput>
}

export type UserGroupRoleBindingUpdateWithWhereUniqueWithoutRoleInput = {
  where: Prisma.UserGroupRoleBindingWhereUniqueInput
  data: Prisma.XOR<Prisma.UserGroupRoleBindingUpdateWithoutRoleInput, Prisma.UserGroupRoleBindingUncheckedUpdateWithoutRoleInput>
}

export type UserGroupRoleBindingUpdateManyWithWhereWithoutRoleInput = {
  where: Prisma.UserGroupRoleBindingScalarWhereInput
  data: Prisma.XOR<Prisma.UserGroupRoleBindingUpdateManyMutationInput, Prisma.UserGroupRoleBindingUncheckedUpdateManyWithoutRoleInput>
}

export type UserGroupRoleBindingScalarWhereInput = {
  AND?: Prisma.UserGroupRoleBindingScalarWhereInput | Prisma.UserGroupRoleBindingScalarWhereInput[]
  OR?: Prisma.UserGroupRoleBindingScalarWhereInput[]
  NOT?: Prisma.UserGroupRoleBindingScalarWhereInput | Prisma.UserGroupRoleBindingScalarWhereInput[]
  roleId?: Prisma.StringFilter<"UserGroupRoleBinding"> | string
  groupId?: Prisma.StringFilter<"UserGroupRoleBinding"> | string
  createdAt?: Prisma.DateTimeFilter<"UserGroupRoleBinding"> | Date | string
}

export type UserGroupRoleBindingCreateWithoutGroupInput = {
  createdAt?: Date | string
  role: Prisma.RoleCreateNestedOneWithoutGroupBindingsInput
}

export type UserGroupRoleBindingUncheckedCreateWithoutGroupInput = {
  roleId: string
  createdAt?: Date | string
}

export type UserGroupRoleBindingCreateOrConnectWithoutGroupInput = {
  where: Prisma.UserGroupRoleBindingWhereUniqueInput
  create: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutGroupInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutGroupInput>
}

export type UserGroupRoleBindingCreateManyGroupInputEnvelope = {
  data: Prisma.UserGroupRoleBindingCreateManyGroupInput | Prisma.UserGroupRoleBindingCreateManyGroupInput[]
}

export type UserGroupRoleBindingUpsertWithWhereUniqueWithoutGroupInput = {
  where: Prisma.UserGroupRoleBindingWhereUniqueInput
  update: Prisma.XOR<Prisma.UserGroupRoleBindingUpdateWithoutGroupInput, Prisma.UserGroupRoleBindingUncheckedUpdateWithoutGroupInput>
  create: Prisma.XOR<Prisma.UserGroupRoleBindingCreateWithoutGroupInput, Prisma.UserGroupRoleBindingUncheckedCreateWithoutGroupInput>
}

export type UserGroupRoleBindingUpdateWithWhereUniqueWithoutGroupInput = {
  where: Prisma.UserGroupRoleBindingWhereUniqueInput
  data: Prisma.XOR<Prisma.UserGroupRoleBindingUpdateWithoutGroupInput, Prisma.UserGroupRoleBindingUncheckedUpdateWithoutGroupInput>
}

export type UserGroupRoleBindingUpdateManyWithWhereWithoutGroupInput = {
  where: Prisma.UserGroupRoleBindingScalarWhereInput
  data: Prisma.XOR<Prisma.UserGroupRoleBindingUpdateManyMutationInput, Prisma.UserGroupRoleBindingUncheckedUpdateManyWithoutGroupInput>
}

export type UserGroupRoleBindingCreateManyRoleInput = {
  groupId: string
  createdAt?: Date | string
}

export type UserGroupRoleBindingUpdateWithoutRoleInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  group?: Prisma.UserGroupUpdateOneRequiredWithoutRoleBindingsNestedInput
}

export type UserGroupRoleBindingUncheckedUpdateWithoutRoleInput = {
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserGroupRoleBindingUncheckedUpdateManyWithoutRoleInput = {
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserGroupRoleBindingCreateManyGroupInput = {
  roleId: string
  createdAt?: Date | string
}

export type UserGroupRoleBindingUpdateWithoutGroupInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.RoleUpdateOneRequiredWithoutGroupBindingsNestedInput
}

export type UserGroupRoleBindingUncheckedUpdateWithoutGroupInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserGroupRoleBindingUncheckedUpdateManyWithoutGroupInput = {
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserGroupRoleBindingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  roleId?: boolean
  groupId?: boolean
  createdAt?: boolean
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  group?: boolean | Prisma.UserGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userGroupRoleBinding"]>

export type UserGroupRoleBindingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  roleId?: boolean
  groupId?: boolean
  createdAt?: boolean
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  group?: boolean | Prisma.UserGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userGroupRoleBinding"]>

export type UserGroupRoleBindingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  roleId?: boolean
  groupId?: boolean
  createdAt?: boolean
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  group?: boolean | Prisma.UserGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userGroupRoleBinding"]>

export type UserGroupRoleBindingSelectScalar = {
  roleId?: boolean
  groupId?: boolean
  createdAt?: boolean
}

export type UserGroupRoleBindingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"roleId" | "groupId" | "createdAt", ExtArgs["result"]["userGroupRoleBinding"]>
export type UserGroupRoleBindingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  group?: boolean | Prisma.UserGroupDefaultArgs<ExtArgs>
}
export type UserGroupRoleBindingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  group?: boolean | Prisma.UserGroupDefaultArgs<ExtArgs>
}
export type UserGroupRoleBindingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  group?: boolean | Prisma.UserGroupDefaultArgs<ExtArgs>
}

export type $UserGroupRoleBindingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserGroupRoleBinding"
  objects: {
    /**
     * The granted role.
     */
    role: Prisma.$RolePayload<ExtArgs>
    /**
     * The user group receiving the role.
     */
    group: Prisma.$UserGroupPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    /**
     * The ID of the granted role.
     */
    roleId: string
    /**
     * The ID of the user group receiving the role.
     */
    groupId: string
    /**
     * The time when the user group role binding was created.
     */
    createdAt: Date
  }, ExtArgs["result"]["userGroupRoleBinding"]>
  composites: {}
}

export type UserGroupRoleBindingGetPayload<S extends boolean | null | undefined | UserGroupRoleBindingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload, S>

export type UserGroupRoleBindingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserGroupRoleBindingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserGroupRoleBindingCountAggregateInputType | true
  }

export interface UserGroupRoleBindingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserGroupRoleBinding'], meta: { name: 'UserGroupRoleBinding' } }
  /**
   * Find zero or one UserGroupRoleBinding that matches the filter.
   * @param {UserGroupRoleBindingFindUniqueArgs} args - Arguments to find a UserGroupRoleBinding
   * @example
   * // Get one UserGroupRoleBinding
   * const userGroupRoleBinding = await prisma.userGroupRoleBinding.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserGroupRoleBindingFindUniqueArgs>(args: Prisma.SelectSubset<T, UserGroupRoleBindingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserGroupRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserGroupRoleBinding that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserGroupRoleBindingFindUniqueOrThrowArgs} args - Arguments to find a UserGroupRoleBinding
   * @example
   * // Get one UserGroupRoleBinding
   * const userGroupRoleBinding = await prisma.userGroupRoleBinding.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserGroupRoleBindingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserGroupRoleBindingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserGroupRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserGroupRoleBinding that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupRoleBindingFindFirstArgs} args - Arguments to find a UserGroupRoleBinding
   * @example
   * // Get one UserGroupRoleBinding
   * const userGroupRoleBinding = await prisma.userGroupRoleBinding.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserGroupRoleBindingFindFirstArgs>(args?: Prisma.SelectSubset<T, UserGroupRoleBindingFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserGroupRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserGroupRoleBinding that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupRoleBindingFindFirstOrThrowArgs} args - Arguments to find a UserGroupRoleBinding
   * @example
   * // Get one UserGroupRoleBinding
   * const userGroupRoleBinding = await prisma.userGroupRoleBinding.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserGroupRoleBindingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserGroupRoleBindingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserGroupRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserGroupRoleBindings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupRoleBindingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserGroupRoleBindings
   * const userGroupRoleBindings = await prisma.userGroupRoleBinding.findMany()
   * 
   * // Get first 10 UserGroupRoleBindings
   * const userGroupRoleBindings = await prisma.userGroupRoleBinding.findMany({ take: 10 })
   * 
   * // Only select the `roleId`
   * const userGroupRoleBindingWithRoleIdOnly = await prisma.userGroupRoleBinding.findMany({ select: { roleId: true } })
   * 
   */
  findMany<T extends UserGroupRoleBindingFindManyArgs>(args?: Prisma.SelectSubset<T, UserGroupRoleBindingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserGroupRoleBinding.
   * @param {UserGroupRoleBindingCreateArgs} args - Arguments to create a UserGroupRoleBinding.
   * @example
   * // Create one UserGroupRoleBinding
   * const UserGroupRoleBinding = await prisma.userGroupRoleBinding.create({
   *   data: {
   *     // ... data to create a UserGroupRoleBinding
   *   }
   * })
   * 
   */
  create<T extends UserGroupRoleBindingCreateArgs>(args: Prisma.SelectSubset<T, UserGroupRoleBindingCreateArgs<ExtArgs>>): Prisma.Prisma__UserGroupRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserGroupRoleBindings.
   * @param {UserGroupRoleBindingCreateManyArgs} args - Arguments to create many UserGroupRoleBindings.
   * @example
   * // Create many UserGroupRoleBindings
   * const userGroupRoleBinding = await prisma.userGroupRoleBinding.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserGroupRoleBindingCreateManyArgs>(args?: Prisma.SelectSubset<T, UserGroupRoleBindingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserGroupRoleBindings and returns the data saved in the database.
   * @param {UserGroupRoleBindingCreateManyAndReturnArgs} args - Arguments to create many UserGroupRoleBindings.
   * @example
   * // Create many UserGroupRoleBindings
   * const userGroupRoleBinding = await prisma.userGroupRoleBinding.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserGroupRoleBindings and only return the `roleId`
   * const userGroupRoleBindingWithRoleIdOnly = await prisma.userGroupRoleBinding.createManyAndReturn({
   *   select: { roleId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserGroupRoleBindingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserGroupRoleBindingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserGroupRoleBinding.
   * @param {UserGroupRoleBindingDeleteArgs} args - Arguments to delete one UserGroupRoleBinding.
   * @example
   * // Delete one UserGroupRoleBinding
   * const UserGroupRoleBinding = await prisma.userGroupRoleBinding.delete({
   *   where: {
   *     // ... filter to delete one UserGroupRoleBinding
   *   }
   * })
   * 
   */
  delete<T extends UserGroupRoleBindingDeleteArgs>(args: Prisma.SelectSubset<T, UserGroupRoleBindingDeleteArgs<ExtArgs>>): Prisma.Prisma__UserGroupRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserGroupRoleBinding.
   * @param {UserGroupRoleBindingUpdateArgs} args - Arguments to update one UserGroupRoleBinding.
   * @example
   * // Update one UserGroupRoleBinding
   * const userGroupRoleBinding = await prisma.userGroupRoleBinding.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserGroupRoleBindingUpdateArgs>(args: Prisma.SelectSubset<T, UserGroupRoleBindingUpdateArgs<ExtArgs>>): Prisma.Prisma__UserGroupRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserGroupRoleBindings.
   * @param {UserGroupRoleBindingDeleteManyArgs} args - Arguments to filter UserGroupRoleBindings to delete.
   * @example
   * // Delete a few UserGroupRoleBindings
   * const { count } = await prisma.userGroupRoleBinding.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserGroupRoleBindingDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserGroupRoleBindingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserGroupRoleBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupRoleBindingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserGroupRoleBindings
   * const userGroupRoleBinding = await prisma.userGroupRoleBinding.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserGroupRoleBindingUpdateManyArgs>(args: Prisma.SelectSubset<T, UserGroupRoleBindingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserGroupRoleBindings and returns the data updated in the database.
   * @param {UserGroupRoleBindingUpdateManyAndReturnArgs} args - Arguments to update many UserGroupRoleBindings.
   * @example
   * // Update many UserGroupRoleBindings
   * const userGroupRoleBinding = await prisma.userGroupRoleBinding.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserGroupRoleBindings and only return the `roleId`
   * const userGroupRoleBindingWithRoleIdOnly = await prisma.userGroupRoleBinding.updateManyAndReturn({
   *   select: { roleId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserGroupRoleBindingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserGroupRoleBindingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserGroupRoleBinding.
   * @param {UserGroupRoleBindingUpsertArgs} args - Arguments to update or create a UserGroupRoleBinding.
   * @example
   * // Update or create a UserGroupRoleBinding
   * const userGroupRoleBinding = await prisma.userGroupRoleBinding.upsert({
   *   create: {
   *     // ... data to create a UserGroupRoleBinding
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserGroupRoleBinding we want to update
   *   }
   * })
   */
  upsert<T extends UserGroupRoleBindingUpsertArgs>(args: Prisma.SelectSubset<T, UserGroupRoleBindingUpsertArgs<ExtArgs>>): Prisma.Prisma__UserGroupRoleBindingClient<runtime.Types.Result.GetResult<Prisma.$UserGroupRoleBindingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserGroupRoleBindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupRoleBindingCountArgs} args - Arguments to filter UserGroupRoleBindings to count.
   * @example
   * // Count the number of UserGroupRoleBindings
   * const count = await prisma.userGroupRoleBinding.count({
   *   where: {
   *     // ... the filter for the UserGroupRoleBindings we want to count
   *   }
   * })
  **/
  count<T extends UserGroupRoleBindingCountArgs>(
    args?: Prisma.Subset<T, UserGroupRoleBindingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserGroupRoleBindingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserGroupRoleBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupRoleBindingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserGroupRoleBindingAggregateArgs>(args: Prisma.Subset<T, UserGroupRoleBindingAggregateArgs>): Prisma.PrismaPromise<GetUserGroupRoleBindingAggregateType<T>>

  /**
   * Group by UserGroupRoleBinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupRoleBindingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupRoleBindingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupRoleBindingGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupRoleBindingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupRoleBindingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupRoleBindingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserGroupRoleBinding model
 */
readonly fields: UserGroupRoleBindingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserGroupRoleBinding.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserGroupRoleBindingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  role<T extends Prisma.RoleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoleDefaultArgs<ExtArgs>>): Prisma.Prisma__RoleClient<runtime.Types.Result.GetResult<Prisma.$RolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  group<T extends Prisma.UserGroupDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserGroupDefaultArgs<ExtArgs>>): Prisma.Prisma__UserGroupClient<runtime.Types.Result.GetResult<Prisma.$UserGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserGroupRoleBinding model
 */
export interface UserGroupRoleBindingFieldRefs {
  readonly roleId: Prisma.FieldRef<"UserGroupRoleBinding", 'String'>
  readonly groupId: Prisma.FieldRef<"UserGroupRoleBinding", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserGroupRoleBinding", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserGroupRoleBinding findUnique
 */
export type UserGroupRoleBindingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which UserGroupRoleBinding to fetch.
   */
  where: Prisma.UserGroupRoleBindingWhereUniqueInput
}

/**
 * UserGroupRoleBinding findUniqueOrThrow
 */
export type UserGroupRoleBindingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which UserGroupRoleBinding to fetch.
   */
  where: Prisma.UserGroupRoleBindingWhereUniqueInput
}

/**
 * UserGroupRoleBinding findFirst
 */
export type UserGroupRoleBindingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which UserGroupRoleBinding to fetch.
   */
  where?: Prisma.UserGroupRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserGroupRoleBindings to fetch.
   */
  orderBy?: Prisma.UserGroupRoleBindingOrderByWithRelationInput | Prisma.UserGroupRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserGroupRoleBindings.
   */
  cursor?: Prisma.UserGroupRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserGroupRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserGroupRoleBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserGroupRoleBindings.
   */
  distinct?: Prisma.UserGroupRoleBindingScalarFieldEnum | Prisma.UserGroupRoleBindingScalarFieldEnum[]
}

/**
 * UserGroupRoleBinding findFirstOrThrow
 */
export type UserGroupRoleBindingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which UserGroupRoleBinding to fetch.
   */
  where?: Prisma.UserGroupRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserGroupRoleBindings to fetch.
   */
  orderBy?: Prisma.UserGroupRoleBindingOrderByWithRelationInput | Prisma.UserGroupRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserGroupRoleBindings.
   */
  cursor?: Prisma.UserGroupRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserGroupRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserGroupRoleBindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserGroupRoleBindings.
   */
  distinct?: Prisma.UserGroupRoleBindingScalarFieldEnum | Prisma.UserGroupRoleBindingScalarFieldEnum[]
}

/**
 * UserGroupRoleBinding findMany
 */
export type UserGroupRoleBindingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingInclude<ExtArgs> | null
  /**
   * Filter, which UserGroupRoleBindings to fetch.
   */
  where?: Prisma.UserGroupRoleBindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserGroupRoleBindings to fetch.
   */
  orderBy?: Prisma.UserGroupRoleBindingOrderByWithRelationInput | Prisma.UserGroupRoleBindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserGroupRoleBindings.
   */
  cursor?: Prisma.UserGroupRoleBindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserGroupRoleBindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserGroupRoleBindings.
   */
  skip?: number
  distinct?: Prisma.UserGroupRoleBindingScalarFieldEnum | Prisma.UserGroupRoleBindingScalarFieldEnum[]
}

/**
 * UserGroupRoleBinding create
 */
export type UserGroupRoleBindingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingInclude<ExtArgs> | null
  /**
   * The data needed to create a UserGroupRoleBinding.
   */
  data: Prisma.XOR<Prisma.UserGroupRoleBindingCreateInput, Prisma.UserGroupRoleBindingUncheckedCreateInput>
}

/**
 * UserGroupRoleBinding createMany
 */
export type UserGroupRoleBindingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserGroupRoleBindings.
   */
  data: Prisma.UserGroupRoleBindingCreateManyInput | Prisma.UserGroupRoleBindingCreateManyInput[]
}

/**
 * UserGroupRoleBinding createManyAndReturn
 */
export type UserGroupRoleBindingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * The data used to create many UserGroupRoleBindings.
   */
  data: Prisma.UserGroupRoleBindingCreateManyInput | Prisma.UserGroupRoleBindingCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserGroupRoleBinding update
 */
export type UserGroupRoleBindingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingInclude<ExtArgs> | null
  /**
   * The data needed to update a UserGroupRoleBinding.
   */
  data: Prisma.XOR<Prisma.UserGroupRoleBindingUpdateInput, Prisma.UserGroupRoleBindingUncheckedUpdateInput>
  /**
   * Choose, which UserGroupRoleBinding to update.
   */
  where: Prisma.UserGroupRoleBindingWhereUniqueInput
}

/**
 * UserGroupRoleBinding updateMany
 */
export type UserGroupRoleBindingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserGroupRoleBindings.
   */
  data: Prisma.XOR<Prisma.UserGroupRoleBindingUpdateManyMutationInput, Prisma.UserGroupRoleBindingUncheckedUpdateManyInput>
  /**
   * Filter which UserGroupRoleBindings to update
   */
  where?: Prisma.UserGroupRoleBindingWhereInput
  /**
   * Limit how many UserGroupRoleBindings to update.
   */
  limit?: number
}

/**
 * UserGroupRoleBinding updateManyAndReturn
 */
export type UserGroupRoleBindingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * The data used to update UserGroupRoleBindings.
   */
  data: Prisma.XOR<Prisma.UserGroupRoleBindingUpdateManyMutationInput, Prisma.UserGroupRoleBindingUncheckedUpdateManyInput>
  /**
   * Filter which UserGroupRoleBindings to update
   */
  where?: Prisma.UserGroupRoleBindingWhereInput
  /**
   * Limit how many UserGroupRoleBindings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserGroupRoleBinding upsert
 */
export type UserGroupRoleBindingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingInclude<ExtArgs> | null
  /**
   * The filter to search for the UserGroupRoleBinding to update in case it exists.
   */
  where: Prisma.UserGroupRoleBindingWhereUniqueInput
  /**
   * In case the UserGroupRoleBinding found by the `where` argument doesn't exist, create a new UserGroupRoleBinding with this data.
   */
  create: Prisma.XOR<Prisma.UserGroupRoleBindingCreateInput, Prisma.UserGroupRoleBindingUncheckedCreateInput>
  /**
   * In case the UserGroupRoleBinding was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserGroupRoleBindingUpdateInput, Prisma.UserGroupRoleBindingUncheckedUpdateInput>
}

/**
 * UserGroupRoleBinding delete
 */
export type UserGroupRoleBindingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingInclude<ExtArgs> | null
  /**
   * Filter which UserGroupRoleBinding to delete.
   */
  where: Prisma.UserGroupRoleBindingWhereUniqueInput
}

/**
 * UserGroupRoleBinding deleteMany
 */
export type UserGroupRoleBindingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserGroupRoleBindings to delete
   */
  where?: Prisma.UserGroupRoleBindingWhereInput
  /**
   * Limit how many UserGroupRoleBindings to delete.
   */
  limit?: number
}

/**
 * UserGroupRoleBinding without action
 */
export type UserGroupRoleBindingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserGroupRoleBinding
   */
  select?: Prisma.UserGroupRoleBindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserGroupRoleBinding
   */
  omit?: Prisma.UserGroupRoleBindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserGroupRoleBindingInclude<ExtArgs> | null
}
