import type * as runtime from "@prisma/client/runtime/client"
import { PrismaClient as BackendDatabase } from "./_generated/backend/postgresql/client"
import { PrismaClient as ProjectDatabase } from "./_generated/project/client"

export type BackendTransaction = Omit<BackendDatabase, runtime.ITXClientDenyList>
export type ProjectTransaction = Omit<ProjectDatabase, runtime.ITXClientDenyList>

export type {
  BackendApiKey,
  BackendUnlockMethod,
  Library,
  Project,
  ProjectSpace,
  PulumiBackend,
} from "./_generated/backend/postgresql/client"
export type {
  BackendApiKeyCreateInput,
  BackendApiKeyWhereInput,
  BackendRoleCreateInput,
  BackendRoleWhereInput,
  BackendServiceAccountCreateInput,
  BackendServiceAccountWhereInput,
  LibraryCreateInput,
  LibraryWhereInput,
  ProjectModelStorageCreateInput,
  ProjectModelStorageWhereInput,
  ProjectSpaceCreateInput,
  ProjectSpaceWhereInput,
  ProjectWhereInput,
  PulumiBackendCreateInput,
  PulumiBackendWhereInput,
} from "./_generated/backend/postgresql/models"
export type {
  ApiKey,
  Artifact,
  InstanceCustomStatus,
  InstanceEvaluationState,
  InstanceEvaluationStatus,
  InstanceLock,
  InstanceOperationState,
  InstanceOperationStatus,
  InstanceSource,
  InstanceState,
  InstanceStatus,
  Operation,
  OperationLog,
  OperationStatus,
  OperationType,
  Page,
  Panel,
  Secret,
  ServiceAccount,
  Terminal,
  TerminalSession,
  TerminalSessionLog,
  TerminalStatus,
  Trigger,
  UnlockMethod,
  Worker,
  WorkerUnitRegistration,
  WorkerVersion,
  WorkerVersionLog,
} from "./_generated/project/client"
export type {
  ApiKeyWhereInput,
  ArtifactWhereInput,
  EntityOrderByWithRelationInput,
  EntitySnapshotReferenceOrderByWithRelationInput,
  EntitySnapshotReferenceWhereInput,
  EntitySnapshotWhereInput,
  EntityWhereInput,
  InstanceEvaluationStateUncheckedCreateInput,
  InstanceEvaluationStateUpdateInput,
  InstanceOperationStateCreateInput,
  InstanceOperationStateCreateManyInput,
  InstanceOperationStateUpdateInput,
  InstanceStateInclude,
  InstanceStateUpdateInput,
  InstanceStateWhereInput,
  OperationUpdateInput,
  OperationWhereInput,
  PageWhereInput,
  PanelWhereInput,
  RoleCreateInput,
  SecretWhereInput,
  ServiceAccountCreateInput,
  ServiceAccountWhereInput,
  TerminalWhereInput,
  TriggerWhereInput,
  UnlockMethodWhereInput,
  WorkerVersionWhereInput,
  WorkerWhereInput,
} from "./_generated/project/models"
export { DbNull } from "./_generated/project/internal/prismaNamespace"
export { BackendDatabase, ProjectDatabase }
