<script setup lang="ts">
import { SettingsListPage, PagesTable } from "#layers/core/app/features/settings"

const { settingsStore } = useProjectStores()
const { projectStore } = useProjectStores()

if (projectStore.initializing) {
  await until(() => projectStore.initialized).toBe(true)
  projectStore.addLibraryRoot()
} else {
  await projectStore.initialize1()
  await projectStore.initialize2()
}

void settingsStore.pages.load()

definePageMeta({
  name: "settings.pages",
  tab: {
    label: "Pages",
    icon: "mdi-file-document-outline",
    order: 13,
    subpages: ["settings.page-details"],
  },
})
</script>

<template>
  <SettingsListPage
    title="Pages"
    icon="mdi-file-document-outline"
    description="View and manage custom pages generated by your project instances."
  >
    <template #default="{ height }">
      <PagesTable
        v-model:search="settingsStore.pages.search"
        v-model:sort-by="settingsStore.pages.sortBy"
        v-model:page="settingsStore.pages.page"
        v-model:items-per-page="settingsStore.pages.itemsPerPage"
        :project-id="projectStore.projectId"
        :data="settingsStore.pages.data"
        :loading="settingsStore.pages.isLoading"
        :height="height"
      />
    </template>
  </SettingsListPage>
</template>
