name: Verify

on: [pull_request]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --unshallow --tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Restore Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/berry/cache
            .yarn/install-state.gz
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Verify
        run: |
          npx nx-cloud start-ci-run --auto-apply-fixes="*test*,*biome:check*" --no-distribution
          yarn ci:verify
          npx nx-cloud stop-all-agents

      - name: Fix CI (if needed)
        run: npx nx fix-ci
        if: always()
