name: Verify

on: [ pull_request ]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Nix
        uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1

      - name: Configure devenv cache
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: devenv

      - name: Fetch all tags
        run: git fetch --unshallow --tags

      - name: Install devenv
        run: |
          devenv_rev="$(jq -r '.nodes.devenv.locked.rev' devenv.lock)"
          nix profile add "github:cachix/devenv/${devenv_rev}"

      - name: Build CI environment
        run: devenv shell --profile ci -- true

      - name: Install dependencies
        shell: devenv shell --profile ci bash -- -e {0}
        run: bun install --frozen-lockfile

      - name: Prepare
        shell: devenv shell --profile ci bash -- -e {0}
        run: bun run ci:prepare

      - name: Verify
        shell: devenv shell --profile ci bash -- -e {0}
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
        run: bun run ci:verify
