name: Verify

on: [pull_request]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --unshallow --tags

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          package-manager-cache: false

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Dependency Cache
        uses: actions/setup-node@v5
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Verify
        run: |
          pnpm nx-cloud start-ci-run --auto-apply-fixes="*test*,*biome:check*" --no-distribution
          pnpm ci:verify
          pnpm nx-cloud stop-all-agents

      - name: Fix CI (if needed)
        run: pnpm nx fix-ci
        if: always()
